The first step in learning Divine Magic is to join a religion that
worships the deity whose magic the character wants to learn.

Religions

Religions can range in size from a handful of worshippers to millions of
adherents. They teach their members Personal Magic associated with the
god and provide temples where worshippers can learn Divine Magic
directly from their deity. They have rules for and expectations of their
worshippers, and anyone found wanting is expelled from the comfort and
support of the religion.

Religions take one of two forms, Pantheon or Dedicated.

_Pantheon religions_ are the worship of many gods, and such groups of
gods usually have a ruling deity. Worshippers of this kind of religion
usually get a little bit of magic from each of the deities.

_Dedicated religions_ are the worship of one particular deity. The deity
may be associated with one or more pantheons and may provide some magic
to worshippers of these pantheons, but dedicated religions focus on the
individual deity and all its myths and mysteries. As a result,
worshippers get the full range of magic that the deity knows.

Characters may be members, at any rank, of both a Pantheon religion and
a Dedicated religion of one of the associated deities.

Each religion description uses the following format.

_Name of the Deity or Religion:_ The name that the religion is commonly
known by, usually the name of the deity that it worships.

_Short description:_ This short description briefly covers the
religion’s mythology and its current place in the world.

_Type of religion:_ Pantheon or Dedicated.

_Scale of worship:_ This is the type and size of the religion. Great
Deities are worshipped by millions and known across the entire world.
Major Deities are important in a specific region and have hundreds of
thousands of worshippers. Minor Deities are usually the minor members of
a religious pantheon, appealing to a small group of specialist
worshippers. Hero Religions worship dead heroes and heroines whose deeds
and magic powers live on after their death.

_Worshippers:_ The type of people who typically make up the religion’s
membership.

_Worshipper duties:_ This is what the god and religion expect of its
members. Break these rules and expect expulsion. On the other hand,
follow these rules and promote them to others and the character will
advance in the religion’s hierarchy.

_Religious skills:_ These are skills favoured by the religion’s patron
deity and taught to its worshippers by its Priestesses/Priests.

_Religious magic:_ A religion’s spells __are u__sually made up of
Personal Magic and the Divine Magic that the religion teaches. Both
types are available if appropriate to the god’s sphere of influence.

For example, A war god is likely to teach Weapon Enhance (Personal
Magic) and Berserk rather than Healing spells.

_Special benefits:_ Any bonuses to skill use or other special abilities
or advantages that a worshipper gains by being a member of the religion.

Growth and Worshipper Duties

Each religion has a set of worshipper duties which represent the
religion’s objectives in the world.

When a character does an action that fulfils one of the worshipper
duties, they gain one growth for a minor action and up to three points
for a major act.

When a character takes an action that goes against one of the worshipper
duties, they lose between one and three growth points, depending on the
grievousness of their transgression. If they have no growth points left,
then they start to lose points of magnitude learnt from the religion as
a penance, on a one to one basis. The player may choose which spells to
lose, but they must be ones that they have learnt from the religion, and
Divine Magic is lost before Personal Magic spells.

If the offending character has no growth points or spells to lose, then
they are excommunicated from the religion and may never join it again.

Religious Ranks

There are four ranks of religion membership: Lay Members, Initiates,
Priests and Holy Warriors.

*Lay Members*

Lay members are normal worshippers of the religion, who self-identify as
members of that religion. They regularly attend the temple on holy days
and do their best to uphold the duties of the religion. In return, the
religion protects them as best it can, and its Priest and Initiates cast
magic on their behalf.

*Benefits of Being a Lay Member*

_Personal Magic:_ Lay members cannot learn Divine Magic, although, for a
fee, represented by spending growth points, they may learn low magnitude
(no more than magnitude 2) Personal Magic spells if known to the
religion. 

_Protection:_ Officials of the religion do their best to protect lay
members. Religious spell casters will cast magic on their behalf at no
cost.

_Requirements:_ To be considered a Lay Member of a Religion, the
character must broadly uphold the worshipper duties of the religion and
have the appropriate Religion skill at least 20%.

*Initiates*

Initiates are worshippers who have dedicated their lives to the creed of
the religion and have taken part in a formal initiation ceremony to
initiate them into the inner mysteries of the religion. They are
expected to actively live the lifestyle that their religion promotes,
and learn the religion’s mysteries. They are an example to the lay
members and in smaller settlements, such as rural villages, they often
take the role of the Priest in leading services on holy days at the
local shrine.

_Requirements:_ The relevant Religion skill must be a minimum of 40%,
and an Initiate must have one of the religion’s skills at a minimum of
25%. Also, the character must spend two growth points on becoming
initiated. An initiate must uphold the religion’s worshipper duties.

*Benefits of Being an Initiate*

_Learn Personal Magic_: Initiates can learn any Personal Magic spell the
religion teaches at unlimited magnitude.

_Learn Divine Magic:_ Initiates may learn any Divine Magic spell
available to the religion up to magnitude 2.

_Protection:_ As lay members; plus they get free lodging or use of any
buildings that the religion owns. Great religions will often have
lodging houses, especially for travelling initiates.

*Priests*

These people are the living embodiment of their faith, instructed by
their deity to be its living representatives in the mortal world.  They
lead the services for their temple on holy days and are leaders in their
community.

_Requirements:_ To become a Priest, a character must have the Religion
skill and two of the religion’s associated skills at a minimum of 75%;
there must also be a vacancy in the temple hierarchy, or the new Priest
be willing to become a missionary and establish a new temple. Besides
all this, the player must pay five growth points.

*Benefits of being a Priest*

_Ransom:_ The religion will pay the ransom if a priest is captured, or
make all reasonable attempts to rescue them.

_Learning Personal Magic & Divine Magic:_ A priest may learn all the
inner secrets of their religion (this means all available magic at
unlimited magnitude). They may also get Divine Magic spells available
only to their rank if such spells are listed for the religion.

_Allied Spirit:_ Upon becoming a Priest, the character gains an Allied
Spirit. An Allied Spirit is a spirit associated with the deity who is
willing to work with one of their mortal worshippers to further the aims
of the religion. The Allied Spirit is usually bound in either an animal
or an item, sacred to the religion.

If the vessel the spirit lives in, item or animal, is destroyed, then
the Allied Spirit returns to its home plane of existence and then
returns when a new animal or item is prepared for it.

In the case where Allied Spirit has its magic points reduced to zero,
i.e. destroyed, in service, a new Allied Spirit is assigned to the
Priest/Priestess.

An Allied Spirit starts with an INT of 2D6+6 and a POW of 3D6 and knows
6 points of Personal Magic and 3 points of Divine Magic known to the
religion. The spirit can see immaterial and invisible spirits, alerting
its master to their presence in a twenty-metre range. An Allied Spirit
is in permanent Mind Link with its master, with a range equal to its POW
x5 in meters.

An Allied Spirit has whatever physical characteristics that its host
animal or item has.

Allied Spirits are advanced like player characters, by spending growth
points from their Priest’s total.

*Holy Warriors*

Holy Warriors who protect the temples and worshippers of their religion.
Not all religions have Holy Warriors, especially those religions
dedicated to peace, but where they do, these warriors ceaselessly
crusade to protect the faithful and punish the religion’s enemies.

The minimum requirement to become a Holy Warrior is to have Religion of
at least 50% and a combat skill of at least 75%. Besides this, the
player must pay five growth points.

_Requirements:_ Uphold the worshipper duties unfailingly. As the
religion’s warriors, take up arms against any aggressor who attacks its
worshippers or the religion’s temples.

*Benefits of being a Holy Warrior*

_Holy Arms and Armour:_ When someone becomes a Holy Warrior they are
gifted a specially consecrated weapon, that gives them a bonus when
fighting to defend fellow worshippers, religious temples, and when
attacking enemies of their faith. This bonus is usually +20% to the
appropriate weapon skill and double damage when fighting for their
religion. All damage done by such weapons is considered magical.

They also gain armour, which is magically blessed by the religion’s
deity. Usually, this is at least double the normal AP of the armour type
used, and it may have additional powers depending on the deity.

_Learn Personal Magic & Divine Magic:_ Holy Warriors may learn all the
spells available to the religion as Initiates.

_Learn Special Divine Magic: Holy Warriors_ may get additional Divine
Magic spells that further enhance their ability to fight on behalf of
the religion, at unlimited magnitude. These specific spells are listed
for the Holy Warrior. Otherwise, they get the listed divine Magic at a
maximum of 2 magnitude.

_Ransom:_ Holy Warriors are incredibly useful to the religion they
belong to, which will always pay any ransom or make a rescue attempt if
a Holy Warrior is ever captured.

*Warrior Priests*

Usually, a character cannot be both a Priest and a Holy Warrior. Both
are precise roles within the religion which are quite demanding on the
character’s time. Some religions may have more martially inclined
Priestesses/Priests, which combine the functions and abilities of the
Priest with that of a Holy Warrior.

The Universal Earth Mother Religion

The Goddess is the all-embracing and loving Earth Mother worshipped
throughout the world. Some people believe that she is the world itself.
She is the source of all nature’s bounty, which clothes and feeds
humanity, but also has a savage side that expresses itself in
hurricanes, tidal waves and other natural disasters.

_Type of Religion_: Dedicated Religion (Great Deity).

_Scale of Worship:_ Worldwide.

_Worshippers:_ The religion is made up of people and creatures who live
off the land. In civilised areas, these are the peasants who farm the
land and the woodsmen who hunt and gather in the forests. Found wherever
creatures have an acknowledged connection with nature.

_Worshipper duties_: Respect the Earth. Don’t foul or pollute the
environment. Don’t take more from the world than it can regenerate. Do
not needlessly kill or over hunt animals.

_Religious skills:_ Healing, Nature Lore, Resilience.

_Religious magic_

_Personal Magic:_ Heal, Protection.

_Divine Magic:_ All Common spells + Absorption, Berserk, Heal Body.

_Special Benefits_: Any member of this religion gains a +20% bonus to
their Nature Lore, due to their connection to Nature, which they gain
through their relationship with the Earth Mother.

*The Earth Mother Priestess*

These matrons represent the divine Earth Mother at the religion’s
rituals, and she speaks through them.

Earth Mothers usually bind their Allied Spirits into animals local to
their temples, such as cows in urban areas, or foxes and bears in
mountain areas. If a suitable animal is not available, branches taken
from local trees and fashioned into an Earth Wand are satisfactory.

Due to the nature of the religion, most priestesses are female, but very
rarely a male with a strong feminine side will meet the requirements.

*Holy Warriors, The Axe Maidens*

These fierce female warriors protect the holy sites of the Earth Mother
and extract retribution against the violators of the earth.

_Required Combat skill:_ Close Combat at 75%

_Holy Weapon:_ Axes of any type +20% and double damage vs. Religion
enemies.

_Holy Armour:_ Red woad. This mixture of the blood of the religion’s
enemies and the blessed earth is taken from a holy site, such as the
consecrated grounds of an Earth Mother temple, gives a +20% to Dodge
rolls and 6 AP.

_Special Divine Magic:_ Axe Maidens can learn the spells of Earth
Scream, Shield, True Axe.

*Earth Scream*

Area 10m Magnitude 2 Duration 15 Resist Persistence.

When cast the Axe Maiden makes a blood-curdling scream at a group of
enemies. If they are within the area of the spell’s effect, they make a
Persistence test or run away from the Axe Maiden in terror for the
duration of the spell.

Ascension

Through walking the Path of Divine Magic, establishing a relationship
with one or more deities or supernatural guardians of the religions that
they follow, high ranking Priests and Holy Warriors can undergo a
magical process called Ascension, becoming immortal and joining the
deities in the Houses of the Holy.

There are two types of Ascended.

* _Ascended Immortal._ A guardian of the religion that they were part of
in life. They join the Pantheon- becoming a guardian that can be called
upon by worshippers.
* _Ascended Deity._ A deity in their own right who may or may not be
worshipped as part of a pantheon or as a dedicated religion.

*Game Requirements*

To become an Ascended Immortal.

Religion (Own) at 100%.

POW at maximum (21 for humans).

Ten points of the religion’s Divine Magic.

Pay a growth cost of ten points.

To become an Ascended Deity.

Religion (Own) at 100%.

POW at maximum (21 for humans).

One or more Religion (other) at 100%, to understand wider implications
of immortality.

Ten points of the Religion’s Divine magic.

Pay a growth cost of twenty points.

*Other Story Requirements*

As well as these requirements to reach certain numerical scores, there
are also more subjective story requirements. Ascended characters are
expected to be shining examples of their religion. They have undergone
one or more Mythic Journeys (see the spell of the same name) to explore
the Divine Other Worlds and understand myths

It might be because of this that characters never reach the lofty levels
of the Ascended because they do not meet the story requirements.

*The Powers of the Ascended*

Ascended Immortals and Deities both have the following powers.

* The ability to grow Power beyond the normal maximum (21 for humans).
* Immortality; if killed, they return to a safe place in the Houses of
the Holy.
* Immune to disease and poison and mind control spells, like Befuddle,
Madness or Fear.
* Their worshippers may learn any personal magic or Divine Magic spell
that the character knows.
* Also, Ascended Deities may create new Divine Magic spells based upon
their actions in play for ten growth per point of spell.

Like Transcended Sorcerers, Ascension is the pinnacle and ultimate goal
of a character’s career. While it may be fun to play an Ascended
character for a couple of Quests, such characters are usually retired
after that.

*_Summary of Religion Ranks_*

[width="99%",cols="15%,16%,8%,2%,56%,3%",]
|===
|Rank |Minimum Religion (+other requirements) |Growth Cost |Benefits | |

|Lay member |20 % |0 |Learn spells from the religion’s Personal Magic at
magnitude 1-2. | |

|Initiate |40 % (One of the religion’s skills at 25%) |2 a|
Learn spells from the religion’s Personal Magic at unlimited magnitude.

Learn spells from the religion’s Divine at magnitude 1-2.

Religion pays ransom if captured.

| |

|Priest |75 % (Two of the religion’s skills at 75%) |5 a|
Learn spells from Personal Magic and Divine Magic at unlimited
magnitude.

Religion pays ransom if captured.

Gain the religion’s Allied Spirit.

| |

|Holy Warrior |50% (75% in Weapon Skill) |5 a|
Learn spells from the religion’s Personal Magic at unlimited magnitude.

Learn spells from the religion’s Divine Magic at magnitude 1-2.

The character learns special Divine Magic at unlimited magnitude.

The religion pays ransom if captured.

Gain the religion’s Weapon and Armour.

| |

|Ascended Immortal |100% (+100% in two of the Religion’s skills. POW 21)
|10 | |Achieves immortality and joins the deities in the Houses of the
Holy, becoming a member of the Pantheon that they worship. |

|Ascended Deity |100 % (+ 100% in two of the religion’s skills and two
Religion (Other) skills, POW 21+) |20 | |Achieves immortality and joins
the deities in the Houses of the Holy, becoming a distinct deity in
their own right. |
|===

Asking the Deities for Answers

A very powerful ability of all characters who are members of a religion
is the ability to seek answers from the deities that they follow.
Guidance from a religion’s deities is available in two forms.

Using the _Divination_ spell that is available to all Initiates and
Priests as a common Divine Magic spell.

By praying at a temple and _Asking for_ _Divine Guidance_ before going
on a Quest.

_Divination_ is the more direct and powerful method and can be called
upon multiple times during a Quest, as long as the character has the
spell memorised. It can also be called upon by non-player Priests who
have a positive relationship with the character.

_Asking for Divine Guidance_ is very limited and can often be even
vaguer than Divination.

It can only be done once per Quest, usually in the preparation phase of
the Quest.

The character must pray at a temple or shrine of a religion that the
character is a member of.

They must make a successful Religion skill test. Otherwise, complete
silence ensues.

If the test is successful, the deity may only answer in the form of
hints and vague symbolic suggestions.

It’s useful if the Referee has a table of random answers – a sort of
rumour table of the Gods – pre-written as part of their Quest
preparation. Alternatively, a quick bullet point list of what the
Deities of a particular temple can tell their worshippers about a Quest
from their own bias can be made.

Learning Divine Magic

To learn Divine Magic spells the caster must meet the following
requirements:

The caster must be an Initiate, Holy Warrior or Priest within a religion
that teaches the spell the character wants to learn.

The character must pay a cost in growth points, equal to twice the
magnitude of the spell, to the deity. Incremental purchase of spells is
allowed, e.g. the player buys Shield 1 for two growth points and then
later increases this to Shield 3, by spending an additional four points.

Casting Divine Magic

Divine magic has the following characteristics when casting.

A character must be able to gesture with their hands and be able to
chant to cast a spell.

Whenever casting a Divine Magic spell, there will always be a sight and
sound that nearby creatures can detect, be it a flash of light, a crack
of thunder or shimmering in the air. The exact effects are up to the
Referee and player to decide but the caster will automatically be
detected by any creatures within ten times the magnitude of the spell,
in metres.

Casting Divine Magic is automatically successful and does not cost any
magic points when it is cast, since its source is the deity. Divine
magic spells always take only a single combat action to cast and take
place on the character’s Influence skill in combat order.

Having cast a Divine Magic spell the character must perform worshipper
duties in downtime to regain the spell; see below for details.

If a spell has variable magnitude and the character knows it at a high
magnitude, it can be cast multiple times (see Splitting Magnitude
below).

Regaining Cast Divine Magic

Normally Divine Magic is regained during the downtime between
adventures. A character will visit their religion’s temples or shrines
and regain their magic by participating in quiet contemplation or
ecstatic worship as is appropriate to their religion.

In-game characters may regain Divine Magic by one of two ways.

* Each time the character successfully performs a worshipper duty, the
character regains the choice of one of their spent spells.
* They may also call on their deity and spend a point of Fortune to
regain a spent spell of their choosing.

Limitations

Divine Magic spells do not stack, e.g. Shield 1 + Shield 2 does not
equal Shield 3.

Dismissing Divine Magic Spells

A caster can dismiss any spell with the Permanent or Duration trait that
they have cast as a single combat action. Ceasing to cast a
Concentration spell is an immediate free action.

Splitting Magnitude

Divine magic allows the caster to ‘split’ a spell’s magnitude into
multiple spells. For instance, if the caster knows the Absorption spell
at magnitude 3, they may choose to cast it as a single magnitude 3
spell, or they may split it into three magnitude 1 Absorption spells, or
one magnitude 1 and one magnitude 2 Absorption spell.

The Power of Divine Magic

When in a direct contest with other forms of magic, Divine Magic has
double its normal magnitude.

Spell Traits

The traits used by Divine Magic spells are detailed below.

Area (X): The spell affects all targets within a radius specified in
metres.

_Concentration:_ The spell’s effects will remain in place so long as the
character concentrates on it. Concentrating on a spell is functionally
identical to casting the spell, requiring the caster to continue to
gesture with both arms, chant, and ignore distractions.

_Duration (X)_: The spell’s effects will stay in place for the number of
minutes indicated.

_Instant:_ The spell’s effects take place instantly. The spell itself
then disappears.

_Magnitude (X)_: The strength and power of the spell. Also, the minimum
number of magic points required to cast it.

_Non-Variable:_ The spell costs the stated magnitude, which may not be
increased or decreased.

_Permanent:_ The spell’s effects remain in place until they are
dispelled or dismissed.

_Progressive:_ This indicates that the spell can be learnt and cast at
greater levels of magnitude than the minimum.

_Ranged:_ These spells have a maximum distance of the character’s POW x
5 in metres.

_Resist (Dodge/Persistence/Resilience):_ The spell’s effects do not take
effect automatically. The target may make a Dodge, Persistence or
Resilience test (as specified by the spell) in order to avoid the effect
of the spell entirely. Note that Resist (Dodge) spells require the
target to be able to use Reactions to Dodge. In the case of Area spells,
the Resist (Dodge) trait requires the target to dive to avoid the
spell’s effect.

_Touch:_ These spells require the character to actually touch their
target for the spell to take effect. The caster must remain in physical
contact with the target for the entire casting.

_Common:_ If the spell Common spell, available to learn from all
religions. Here’s a quick list for reference:

____
Consecrate, Create Blessed Item, Create Idol, Dismiss Magic, Divination,
Excommunicate, Exorcism, Extension, Mindlink, Soul Sight, +
Spirit Block, Mythic Journey.
____

_Variable:_ The spell has a non-set magnitude.

== Spell Descriptions 

Absorption

Duration 15, Magnitude 1, Progressive, Touch

This spell absorbs incoming spells aimed at the target or their
equipment, converting their magical energy into magic points which are
then available to the target. Once cast on a subject, Absorption will
attempt to absorb the effects of any spells cast at the target. It will
not have any effect on spells that are already affecting a character.
The effects of Absorption depend on the relative magnitude of both
itself and the incoming spell – see the Absorption Results table for
more details. Any spell absorbed by this spell is cancelled and does not
affect the target.

*_Absorption Results_*

[width="100%",cols="61%,39%",]
|===
|Incoming Spell’s Magnitude is |Effect

|Equal to or weaker than Absorption’s magnitude. |Incoming spell
absorbed and Absorption remains.

|1 or more points stronger than Absorption’s magnitude. |Absorption
eliminated and incoming spell takes effect.
|===

A character may not accumulate more magic points than his POW while
Absorption is in effect – excess magic points garnered through
Absorption simply vanish. Absorption is incompatible with Reflection,
Shield and Spirit Block.

Berserk

Duration 15, Magnitude 2, Non-variable, Touch

The recipient of this spell is overcome with blood-lust, causing them to
disregard their safety and loyalties but imbuing them with tremendous
stamina and combat ability.

The recipient will automatically succeed any Resilience test for the
duration of the spell. The recipient also automatically succeeds at any
Fatigue tests and cannot be rendered unconscious. The Close Combat
skills of the recipient receive a +50% bonus for the spell’s duration.

However, the subject may not Parry, Dodge or cast any magic spells while
under the influence of Berserk. Normally, the recipient remains in the
Berserk state for the entire 15-minute duration of the spell. Still,
Referees may allow a Berserk character to shake off the effects with a
Persistence test modified by -50%. At the end of the spell, the
recipient immediately becomes Fatigued.

Berserk does not combine with Fanaticism – Berserk will always take
precedence in such cases.

Block Fertility

Magnitude 3, Non-variable, Permanent

While this spell is in place, the recipient is unable to conceive.
Depending on the view of the recipient, this is a blessing or a curse.
The spell can be dispelled by the caster whenever they want. Otherwise,
the effects of the spell are permanent.

Breathe Water

Duration 15, Magnitude 2, Non-variable, Touch

This spell allows an air-breathing creature to breathe water for the
spell’s duration (the subject will still be able to breathe air as
well). It may also be used upon a water-breathing creature to allow it
to breathe air.

Call (Elemental)

Magnitude 1, Permanent, Progressive

This spell summons and binds to the service of the caster an elemental
from another plane of existence, of size dependent on the magnitude of
the spell.

1 = Small, 2= Medium, 3= Large, 4=Huge

For more details on Elementals, see Chapter 11 ‘Creatures’.

The elemental stays under the control of the Priest until killed, or the
Call spell is dispelled.

To be successfully cast, the spell requires an equal volume of the
source material for the elemental. For example, before a successful
summoning, a Large Undine (Water elemental) requires a pool of water of
at least 50m3.

Call (Undead)

Magnitude 1, Permanent, Progressive

This spell reanimates a dead human corpse and turns it into an undead
creature, of a type determined by the magnitude of the spell.

1 = Skeleton, 2 = Zombie, 5= Ghoul, 8= Vampire

The undead creature stays under the control of the Priest until killed.

Consecrate

Area Special, Common, Magnitude 1, Permanent, Progressive

This spell is as much a part of a temple’s foundation as is its
cornerstone. It creates a sphere with a radius of ten metres per point
of magnitude. The consecrated sphere is sacred to the caster’s god.
Consecrate by itself does nothing to keep outsiders at bay, but the
caster of the spell will know if a spell, spirit or someone who is not a
lay member of his religion, crosses the boundaries of the Consecrate
spell.

Create Blessed Items

Area Special, Common, Magnitude 1, Permanent, Progressive

This spell allows the caster to create items which store Divine Magic
spell(s) that are blessed by a Priest with power from the religion’s
deity.

Only Priests and High Priests can create blessed items.

The enchanter forgets the spell(s) they blessed the item with.

The wielder of the item can cast the spell(s) that has blessed the item
but doing so discharges the item’s power. After discharging it, to
recharge the item, it is taken to a temple of the religion that created
it. This recharge takes as many hours as the magnitude of the spell. If
the magnitude of the spell is higher than two, the consecrating team
must have at least one Priest.

The wielder must be a member of either the religion that created the
blessed item or an allied religion.

Blessed items become protected by the religion’s deity and are
unbreakable by normal non-magical means.

Create Idol

Common, Magnitude 4, Permanent

This spell requires an image of the caster’s god worth 100 GD, specially
consecrated by a Priest reading from the sacred texts of the deity
telling the tales and myths. The idol stores the god’s spells and can be
used by Priest and Initiates to regain spells. It can be used by Lay
Members to receive ‘lessons’, via visions, upon touching the idol. Such
visions will increase the Religion skill of a Lay Member by 1D10% when
exposed to them.

Create the Crystal Ship

Magnitude 4, duration the length of the voyage

From out of the air coalesces the Crystal Ship, a magical vessel that
sails through the air to a single destination preordained by the caster.
The caster need never have been there, but the caster’s deity must know
of it. The ship is about the size of a merchant cog and fitted with no
weapons. Although the ship heads steadily towards the destination, at a
rate of 100 km a day, the fine manoeuvring of the ship is managed by the
thoughts of the caster.

Dismiss Magic

Common, Instant, Magnitude 1, Progressive, Ranged

Dismiss Magic is used either against a general target or a specific
spell and as a reaction when attacked with magic.

When used against a general target, Dismiss Magic will eliminate a
combined magnitude of spells equal to its magnitude, starting with the
most powerful affecting the target. If it fails to eliminate any spell
(because the spell’s magnitude is too high), then its effects
immediately end and it will dispel no more spells.

The caster can also target Dismiss Magic against a single specific
spell. It will work successfully as long as Dismiss Magic’s magnitude
equals or exceeds the target spell’s magnitude.

When used as a defensive reaction against incoming magic, as long as the
attacking caster is within Dismiss Magic’s range, a successful Dismiss
Magic disrupts the other spell and nullifies it.

Divination

Common, Instant, Magnitude 1, Progressive

For each point of the magnitude of this spell, the caster can ask one
question of their deity, which they must answer to the best of their
ability. A deity can only answer questions it knows about, and that
falls within its sphere of power. For example, a Mountain God will know
exactly what is going on its slopes at any given time but will be
completely ignorant about the ocean.

Gods will also commonly ask for a sacrifice of an animal or precious
object worth one gold ducat per question asked. Particularly cruel and
bloodthirsty deities will demand blood sacrifices of sentient beings.

Note, a weaker and less direct form of divination can be obtained at
temples and shrines, without use of this spell. See Asking the Gods
above.

Divine Heal

Instant, Magnitude 2, Non-variable, Touch

This powerful spell instantly heals any lost hit points, even if the
character is mortally wounded, back to their full total. It also cures
any natural disease, i.e. one not caused by a spirit; and any deadly
poison is purged instantly from the character. Any damage or effects
caused by it are removed. 

Enhance Fertility

Magnitude 3, Non-variable, Permanent

This spell makes any one creature more fertile than normal. If it is an
animal that has multiple offspring, then it doubles the number. For
creatures who usually have singular births, it guarantees the conception
and birth of the offspring.

This spell negates the effects of any “Block Fertility” spell.

Enhance Unit

Magnitude 3, Non-variable, Duration 6 hours

For the duration of this spell, a troop of up to thirty soldiers gain
+1D6 damage. Also, they cannot be routed or affected by any mind control
magic (such as Befuddle).

Excommunicate

Common, Magnitude 5, Non-variable, Permanent, Resist (Persistence)

This spell severs the mystical link an Initiate enjoys with their god,
causing the target of the spell to immediately and permanently lose all
Divine Magic from the caster’s religion. The target will never again be
able to learn or use Divine Magic spells from the religion. However,
they will still be able to use their Religion skill for purely academic
purposes.

A Priest of the same religion as the target casts the spell in a
ceremony that takes one hour to cast. The Initiate need not be present.

Exorcism

Common, Concentration, Magnitude 3, Non-variable

A Divine Magic caster can draw out a spirit currently possessing a
mortal being by using this spell. Whether the possession is dominant or
covert is immaterial.

This spell forces a possessing spirit into Spirit Combat (see Combat).
The caster uses his Religion (Own) as the attacking skill in the opposed
contest, as this represents the strength of their faith. If the caster
is successful in defeating the spirit, it is cast out of the victim and
flees. If the caster fails, the spirit remains in the possessed victim.

Extension

Common, Duration Special, Magnitude 1, Progressive

This spell lengthens the duration of any Divine Magic spell with the
Duration trait. Extension, and the spell it is extending, are cast
simultaneously by the caster – this is an exception to the normal rule
that only one Divine Magic spell is cast during a combat round.

Each point of magnitude of the Extension spell doubles the target
spell’s duration. Thus, a magnitude 1 Extension increases Breathe
Water’s Duration to 30 minutes, a magnitude 2 increases it to one hour,
magnitude 3 increases it to two hours, magnitude 4 increases it to four
hours, and so on.

Fear

Instant, Magnitude 1, Ranged, Resist (Persistence), Non-variable

This spell causes the target to become overwhelmed with fear. Fear does
not affect unconscious targets, those without an INT characteristic or
those that are currently under the influence of a Fear spell.

*_Fear Effects_*

[width="100%",cols="25%,75%",]
|===
|Target’s Persistence Test |Effect

|Target fumbles Persistence test |The victim instantly loses half
original hit points damage, as its heart falters. Falls into a coma for
1D12 hours.

|Target fails Persistence test |The victim flees in screaming terror for
combat rounds equal to 20 minus its POW (minimum of one combat round).
The victim will not engage in combat unless forced to and will use the
Run combat action whenever possible (unless a faster mode of egress is
available).

|Target succeeds Persistence test |The victim is shaken and disturbed,
suffering a –20% penalty to all skill tests for combat rounds equal to
20 minus its POW (minimum of one combat round).

|Target critically succeeds Persistence test |The victim is unaffected
by the spell and cannot be affected by further Fear spells for combat
rounds equal to its POW.
|===

Find (Type)

Duration 15, Magnitude 1, Non-variable, Ranged

This spell is several spells, though they all operate in a similar
fashion, which allows the caster to locate the closest target of the
spell within its range. This effect is stopped by a thick substance such
as metal, earth or stone, if it is at least one metre thick. It is also
blocked by Absorption, though the caster will know the target is
somewhere within range (though not its precise location). The separate
Find spells are listed below.

Unlike the Personal Magic Detect spells, the Find spells do not require
concentration on the part of the caster – they simply function and alert
them to the presence of whatever they locate.

_Find Enemy:_ Gives the location of one creature who intends to harm the
caster.

_Find Magic:_ Gives the location of the nearest magic item, magical
creature, or active spell.

_Find (Species):_ Each Find Species spell will give the location of the
nearest creature of the specified species. Examples of this spell
include Find Goblin, Find Dwarf and Find Horse.

_Find Substance:_ Each Find Substance spell will give the location of
the nearest substance of the specified type. Examples of this spell
include Find Coal, Find Gold and Find Wood.

The Referee should provide the rough power of the detected subject (e.g.
‘weak magic’ or ‘rich gold lode’).

Illusion

Duration 15, Magnitude 1, Progressive, Ranged

This spell creates an illusion based on all five senses. The illusion
will seem real and solid unless the person looking at it succeeds in a
Perception test, which is subject to a modifier based on the magnitude
of the spell. If the viewer succeeds in a Perception test, and the
illusion could usually cause damage if believed in, it can no longer
cause damage to that character. As soon as a viewer disbelieves the
illusion, it becomes insubstantial and ghost-like to them.

The magnitude also governs the Size of the illusion. A magnitude 1
Illusion can quite happily create small household items, say a fake
table and chair, but would not be able to create an illusion of a
fire-breathing Dragon.

*_Illusions_*

[width="100%",cols="32%,28%,40%",]
|===
|Magnitude |Modifier to Perception test |Type of illusion possible

|1 |+50 % |Not capable of motion or causing damage. Slightly fuzzy and
unreal round the edges. Limit of SIZ 10.

|2 |+25 % |Some minor discrepancies. Capable of motion, but not of
damage. Limit of SIZ 15.

|3 |0 |Capable of motion and causing damage. Limit of SIZ 20.

|4 |-25 % |Capable of motion and causing damage. Limit of SIZ 30.

|5 |-50 % |Indistinguishable from the real thing, capable of motion and
damage. Limit of SIZ 40.

|+1 |-50% |+10 SIZ per magnitude.
|===

Invisibility

Magnitude 4, Non-Variable, Concentration, Touch, Personal

For the duration of the spell, the recipient is entirely invisible to
sight. They can still be heard, felt or smelled, with a -20% to
Perception tests. Also, if the caster loses concentration, or the
recipient casts a spell or makes an attack, the spell ends. The
recipient also becomes visible immediately after the spell ends, so even
if the caster immediately casts another Invisibility spell, there will
be a delay between castings where the recipient is visible.

Jigsaw

Duration 6 Hours, Magnitude 4, Non-variable

This spell causes the target to fall to pieces upon a failed Persistence
roll. The victim will still be alive but will not require food or water
during the time the spell is in operation. When the spell ends, due to
being dispelled or running out of duration, the victim will die unless
painstakingly put back together beforehand.

Lightning Strike

Instant, Magnitude 1, Progressive, Ranged, Resist (Dodge)

This spell causes a sizzling bolt of lightning to streak from the hand
of the caster toward the target. If the bolt hits, each point of
magnitude of the spell will cause 1D6 damage. Armour Points are not
effective against this damage, and it counts as both magical and
electrical damage.

Madness

Instant, Magnitude 1, Non-variable, Ranged, Resist (Persistence, see
below)

This spell causes the target to lose contact with reality and become a
gibbering loon. Madness does not affect unconscious targets, those
without an INT Characteristic or those that are already under the effect
of a Madness spell.

*_Madness Effects_*

[width="100%",cols="20%,80%",]
|===
|Target’s Persistence Test |Effect

|Target fumbles Persistence test |Victim instantly loses 1D4 INT
permanently and lapses into a catatonic state for minutes equal to 20
minus its POW (minimum of one combat round).

|Target fails Persistence test a|
Victim gibbers and raves uncontrollably for combat rounds equal to 20
minus its POW (minimum of one combat round).

The victim will perform random combat actions during this period.

Roll 1D6.

Move to close combat attack a random target.

Run in a random direction (Roll 1D12 as clock face to determine
direction).

Cast a spell at a random target.

Use ranged attack against a random target.

Shout at a random target.

Change stance.

|Target succeeds Persistence test |The victim is shaken and disturbed,
suffering a –20% penalty to all skill tests for combat rounds equal to
20 minus its POW (minimum of one combat round).

|Target critically succeeds Persistence test |The victim is unaffected
by the spell and cannot be affected by further Madness spells for combat
rounds equal to its POW.
|===

Mindblast

Instant, Magnitude 1, Progressive, Ranged, Resist (Persistence)

This spell applies a penalty to the victim’s INT equal to the magnitude
of the spell. The effect lasts days equal to the Caster’s current CHA.

Mindlink

Duration 15, Magnitude 1, Progressive, Ranged

This spell allows the transmission of conscious thoughts, spell
knowledge, runes and magic points between participants.

Additional points of magnitude allow multiple sets of people to be
linked together, either creating several separate pairs of Mindlinked
people or making the Caster the central hub of a small Mindlink network.
In the second case, only the ‘central’ character is linked directly to
other participants.

Mindlink must be cast upon all participants at the same time and is
limited to consenting participants. Any participant in a Mindlink may
use the spell knowledge and magic points of others they linked to
without consent.

Participants in a Mindlink have a special vulnerability to INT, POW, CHA
and morale-affecting spells. Such a spell cast against any member of a
Mindlink will affect all those connected, though all participants are
entitled to defend themselves individually.

Although participants in a Mindlink share magic points and conscious
thought, they remain their own entity. Mindlink does not include hidden
thoughts, memories, unconscious urges or permanent spell knowledge. A
Mindlink participant may cast a spell using one of those the other
participants have, but only if they have the necessary spell casting
skill – Mindlink does not allow sharing of skills.

Any participant may sever their connection to the Mindlink as a combat
action. If any participant in Mindlink leaves the spell’s range, that
participant has left the Mindlink.

Miraculous Item

Duration 1 hour, Magnitude 1, Progressive

This spell allows the Caster to create items literally from nowhere. The
size of the item depends upon the magnitude of the spell.

*_Magnitude vs. Size of Miraculous Item_*

[width="100%",cols="17%,83%",]
|===
|Magnitude |Size of item

|1 |Small items. Such as pots, plates, knives, and a defaced detail on a
stone fresco, etc.

|2 |Medium. Large containers such as wine amphorae, target shields, long
swords, human-sized armour, a missing arm on a broken statue.

|3 |Large. Tower shields, broken doors, a missing masonry feature such
as a column.

|4 |Huge. Giant armour, ruined houses, shattered towers.

|5 |Enormous. The broken parts of a walking castle, the ruined walls of
a city.
|===

Such items are always of the finest quality and do not break under any
circumstance. For the cost of the magnitude in growth points, the item
can last permanently. Otherwise, it disappears after one hour.

Mythic Journey

Common, Duration 1 Day, Magnitude 4, Non-variable

This spell opens a gate to a place in the Houses of the Holy associated
most closely with the worshipper’s deity or pantheon. The worshipper may
take any number of companions with them but must be aware that if they
are not acceptable to the residents of the place they are going to, they
may be attacked or expelled. Also, the companions must have some strong
spiritual connection with the caster, such as being members of the same
religion or good friends.

Time works differently in the worlds of mythology, perhaps no longer
being a workable concept, but for where time is important, in the Real
World, the spell’s duration is the amount of time that the caster and
their companions are away in the Mythic World.

_For example,_ Ethelred uses this spell to travel to the Palace of the
Celestial Emperor to ask him in person for help in the Real World
against the invading Burning Horde. Once his business has finished
there, he decides to stay and linger enjoying the delights of the Divine
Court. Months pass, or so it seems, until Ethelred loses track of how
many Imperial Banquets he has enjoyed. One morning, instead of waking up
in his crystal room with its bed made of satin sheets, in the palace, he
awakes in the Real World Temple of the Celestial Emperor in one of the
initiates beds, a rather rude affair with rougher linen sheets. He asks
the passing novice how long he has been away and finds out that it’s
only a day after he passed through the gate when he cast the spell.

It is also possible to get trapped in the Mythic World (for example,
through getting captured by magical powers) in which case the character
does not return form the Mythic World until they escape whatever power
that has them in their thrall.

_For example,_ Nykos the Squire accompanies Ethelred to the Palace of
the Celestial Emperor. While his master is conducting his business,
Nykos meets one of the Imperial Handmaidens and becomes beguiled by her
charms. When Ethelred returns to the real world, after months of
pleasure, Nykos remains still under the spell of the Imperial
Handmaiden.

Mischief

Magnitude 2, Non-Variable, Touch, Resist (Persistence)

Mischief is a minor trickster’s spell which afflicts its target with a
small irritating curse.

Roll 1D20 on the following list for a result, which stays in place for
the duration of the spell.

*_Type of Mischief_*

[width="100%",cols="14%,86%",]
|===
|Roll 1D20 |Result

|1 |Clothes disappear.

|2 |Hair goes green.

|3 |Hair drops out.

|4 |Grows beard regardless of sex.

|5 |The target’s weapon becomes a bunch of flowers.

|6 |Armour becomes the festive dress of the opposite sex.

|7 |Feet become duck feet.

|8 |Head becomes that of a domestic animal (cow, pig, sheep, etc.).

|9 |Victim smells of excrement (-20% to any Deception or Influence
rolls).

|10 |Wobbles uncontrollably, -20% to attacks, Athletics and any other
roll involving dexterity.

|11 |The victim can only speak gibberish.

|12 |The victim says the most inappropriate things at the most socially
awkward times. -20% to any Influence rolls.

|13 |The victim falls asleep for 1D6 rounds on failed Persistence roll
whenever they enter combat.

|14 |Makes loud flatulent noises whenever they move; -25 to any
Deception rolls.

|15 |The victim is compelled to tell the truth at all times.

|16 |No one ever takes the character seriously. Always has to make an
Influence roll at -20% to convince others.

|17 |Turns into a dog.

|18 |Arms turn to rubber, unable to hold anything.

|19 |The victim becomes short, half SIZ.

|20 |Roll twice.
|===

Puppet

Concentration, Duration 6 hours, Magnitude 3, Resist (Persistence)

The caster uses this spell to enchant a puppet, which is the focus of
the spell and the stand-in for the victim. The victim can use
Persistence to resist the spell, and if they fail, their actions are
controlled via the puppet by the caster, for the duration of the spell.
The victim is aware of not being in control of their body but is
powerless to stop it. The exception to this rule is when the victim’s
life or that of a friend is in danger because of the Puppeteer’s
commands. Then the victim is allowed another Persistence roll, and, if
successful, break free of the spell’s control.

Purity (Religion/Creed)

Magnitude 2, Touch

This spell removes a perceived sin according to a particular religion.
If the caster is out of favour because of said sin, all is forgotten and
forgiven.

Quicksand

Area, Magnitude 2, Non-Variable

This spell creates a patch of quicksand 10m square. The earth in the
area becomes boggy and saturated with water. On a failed Persistence
roll, any character standing on the patch will sink into the earth, at a
rate of 1 metre a combat round, The quicksand holds the victim firmly
and only by dispelling the magic can they be rescued.

Once the duration of the spell is over, the victim, if not on the
surface, is buried under the now solid earth (see Suffocation rules).

Radiant Appearance

Duration 1 Day, Magnitude 2, Non-Variable

The recipient of this spell glows with light and power. They gain +50%
to any Influence rolls for the duration of the spell. Also, any
light-hating creatures suffer -20% when attacking the recipient.

Repair and Replace

Instant, Magnitude 1, Progressive

This spell repairs broken crafted items. It also replaces missing parts
of an item.

The size of the item depends on the magnitude of the spell.

*_Size of Item vs Magnitude_*

[width="100%",cols="16%,84%",]
|===
|Magnitude |Size of Item

|1 |Small items, such as pots, plates, knives, a defaced detail on a
stone fresco, etc.

|2 |Medium. Large containers, such as wine amphorae, target shields,
long swords, human-sized armour, a missing arm on a broken statue.

|3 |Large. Tower shields, broken doors, a missing masonry feature such
as a column.

|4 |Huge. Giant armour, ruined houses, shattered towers.

|5 |Enormous. The broken parts of a walking castle, the ruined walls of
a city.
|===

Reflection

Duration 15, Magnitude 1, Progressive, Ranged

This spell reflects incoming spells aimed at the target or his
equipment, redirecting the spell back at the original caster. Once cast
on a subject, Reflection will attempt to reflect any spells cast at the
target. It will not have any effect on spells that are already affecting
a character. The effects of Reflection depend on the relative magnitude
of both itself and the incoming spell – see the Reflection Results table
for more details.

Reflection is incompatible with Absorption, Shield and Spirit Block

*_Reflection Results_*

[width="100%",cols="41%,59%",]
|===
|Incoming Spell’s Magnitude is. . . |Effect

|Equal to or weaker than Reflection’s magnitude. |Incoming spell
reflected and Reflection remains.

|1 or more points stronger than Reflection’s magnitude. |Reflection
eliminated and incoming spell takes effect.
|===

Resurrect

Concentration Special, Instant, Magnitude 5, Non-variable, Touch

The body of the deceased must be present and must be whole. If the
target died due to disease or poison, the recipient returns to life
cured.

This spell summons the deceased spirit to return its former body. Taking
minutes equal to the target’s totalled Characteristics to take effect,
during which time the caster must maintain concentration on the spell.
If interrupted, the spell fails. When the spell is successful, the dead
character returns to life with one hit point.

Resurrect must be cast within days equal to the POW of the deceased.
Casting the spell after this point results in the magic automatically
failing.

Rout

Magnitude 3, Non-variable

When aimed at a body of warriors, of no more than one hundred persons,
they must make a Persistence roll or immediately lose all cohesion as a
unit and rout. Routing units move at double movement, away from the
caster, to ideally a place of safety. They will not defend themselves
but will attack any enemy units that get in their way, to get through
them to their place of safety.

See Past

Area, Concentration, Magnitude 2, Non-variable

When cast on a 10m area, the caster, as long as they concentrate, can
see the area as it was in any past point of time they wish. They still
need to make successful Perception rolls to notice details, such as
important clues, and they cannot interact with the scene they see in any
way, shape or form.

Shield

Duration 15, Magnitude 1, Progressive

This spell protects the caster from physical and magical attacks. Each
point of magnitude gives the caster one Armour Point and provides a +10%
bonus to any tests the caster may make to resist malign magical effects.
A magnitude 4 Shield spell provides the caster with +4 AP and a +40%
bonus against malign spells, for instance. These effects are cumulative
with other spells, as well as any physical armour the caster is wearing.
Shield is incompatible with Absorption, Reflection and Spirit Block.

Soul Sight

Common, Duration 15, Magnitude 1, Non-variable, Touch

This spell allows the recipient to see the POW aura of anyone they looks
at, enabling them to discern that creature’s current magic points, as
well as the nature of any active spells or enchanted items the creature
is carrying. It also allows the recipient to see into the Spirit World.

Stink Bomb

Magnitude 1, Resist (Resilience)

Upon being targeted by this spell, the victim becomes covered in a
tightly fitting cloak of noxious smelling gas for 1D6 rounds. Each round
the victim must make a Resilience test or take 1D4 damage. If the
resistance test result is a fumbled, the character is unconscious for
the remaining duration of the spell from being knocked out by the smell.
All Influence tests and other social interactions are at -20% for the
duration of the spell.

Spirit Block

Common, Duration 15, Magnitude 1, Progressive, Touch

Spirits may only touch the recipient of Spirit Block with a POW high
enough to break through the spell’s magnitude (see table).

*_Spirit Block Effectiveness_*

[width="100%",cols="29%,71%",]
|===
|Spirit Block’s Magnitude |Recipient May Only Be Harmed By Spirits With…
|1 |POW 10 or higher
|2 |POW 17 or higher
|3 |POW 26 or higher
|4 |POW 37 or higher
|5 |POW 50 or higher
|6 |POW 65 or higher
|7 |POW 82 or higher
|8 |POW 101 or higher
|===

A spirit unable to touch a Spirit Blocked character will not be able to
personally attack or harm the recipient, including through ranged
attacks (such as a thrown spectral javelin). A spell cast by a spirit at
the recipient is blocked unless its magnitude exceeds Spirit Block’s
magnitude.

Spirit Block is incompatible with Absorption, Reflection and Shield.

Sun Disc

Magnitude 1, Non-variable, Ranged, Resist (Dodge)

Upon casting this spell, the Caster projects a disc of blinding light
from their hand. Targets in the path of the disc are blinded for 1D4
hours, unless they pass their Dodge skill test. Its warming effect melts
ice upon contact, even magical ice, if under three magnitude in power,
and gives anyone it touches +50% resistance versus cold.

Sunspear

Instant, Magnitude 4, Non-variable, Ranged, Resist (Dodge)

This spell will only function in direct sunlight. When cast, a shaft of
light two metres wide streaks from the sky to blast a single target, who
must be visible to the caster. If the target does not dive out of the
way, the blazing light will burn it for 4D6 damage. Armour points are
not effective against this damage, and it counts as both magical and
fire damage.

Sureshot

Duration 15, Magnitude 1, Non-Variable, Ranged

When cast on a missile weapon (such as a knife, arrow, javelin or rock),
firing it triggers the spell. Unless the wielder of the weapon rolls an
automatic failure or a fumble, the missile hits successfully (though it
may be dodged or parried). So long as the target is within the maximum
range of the weapon, the missile will strike home, regardless of
concealment or any other factors. Attempts to parry or dodge the missile
suffer a –20% penalty.

Combining Sureshot with Firearrow, Multimissile or Speedart does not
work, since Sureshot will always take precedence in such cases.

Thunder’s Voice

Magnitude 2, Non-variable

This spell grants the caster a loud voice of command which gives the
caster +20% added to their Influence skill, heard at up to 200 metres.

Touch of Death

Magnitude 4, Non-variable, Touch, Instant, Resist (Persistence)

The caster must touch their victim, and on a failed Persistence test,
the victim falls dead. This incredibly powerful spell is available to
only members of religions whose deity wields the power of death itself.
Usually, to redress the balance, where a person who by all rights should
be dead is still alive.

Treasury

Duration 1-day Magnitude 4

This spell creates a secure room, for one day, to store valuables. All
the entrances are locked and only the caster can come in and out without
setting off a magical alarm that they can hear, no matter how far away
from the room they are.

True (Weapon)

Duration 15 minutes, Magnitude 3 Non-variable, Ranged

When cast on the specified type of weapon, this spell doubles that
weapon’s normal damage dice. Other modifiers, such as Damage Modifier,
are not affected. The wielder of the weapon should roll the weapon’s
damage twice and total the result.

Ward Camp

Area, Duration eight hours, Magnitude 2, Non-variable

This spell protects a camp with an area of 50 meters squared. Anyone
crossing the invisible boundary of the spell takes 1D10 damage and sets
off a magical alarm that immediately awakens everyone within the camp.
The Ward stays in place, even after it has been crossed, for the full
duration of the spell.

Wax Effigy

Magnitude 4, Non-variable, Resist (Persistence)

This spell enchants a small wax representation of the intended victim.
Spells can be cast at the effigy and affect the victim, despite the
distance between the effigy and the victim. The caster need not have
seen/met the victim, since it is the power of their god that is
providing the link. Once a day, the victim can be caused physical harm
by driving pins into the effigy, at 1D4 damage per pin. The caster can
attempt to kill the victim outright by breaking off the head of the
effigy. In this case, the victim gets a Persistence roll to avoid death.
On a failed Persistence test, the victim dies. On a successful
Persistence roll, the effigy no longer has any power over the victim.

Whirlwind

Magnitude 1, Duration 15 minutes, Progressive

Each point of magnitude of this spell whips up a whirlwind capable of
carrying 20 SIZ in its whirling vortex. Each round the whirlwind moves
ten metres per point, in a random direction (use a D8 to determine the
direction, with 1 being North and 5 being South, progressing clockwise
around the directions). For each point of magnitude the whirlwind is 10
metres tall.

If the whirlwind hits a character, make a Dodge roll to avoid being
caught up in it. Characters caught are whipped off their feet, 1D6
metres into the vortex. Each round roll a 1D6 and consult the following
table.

*_Whirlwind Results_*

[width="100%",cols="12%,88%",]
|===
|Roll 1D6 |Result

|1-2 |The character is carried up 1D10 metres (if already at the top,
blown out of the whirlwind the additional height before falling to earth
(taking damage).

|3-4 |Stay at the height they are.

|5-6 |Fall 1D6 down in the vortex. If this takes them to the ground,
they take falling damage.
|===
