The Creature List

Each of the following creatures is described in the following format.

Characteristics

These are the characteristics that the creature possesses. If a creature
is missing a characteristic for any reason, the effect of this is noted
under the Special rules section for that creature. Two scores are given
for each characteristic. Firstly, the dice range which you can roll to
determine an individual’s characteristics randomly, and in brackets the
score of an average individual of that species. This average score is
used throughout the rest of the stats, so you can quickly pick up and
use the creatures. If you randomly roll characteristics, you will have
to adjust the rest of the skills and other characteristic dependent
scores accordingly.

A creature with a randomly determined INT is considered sentient – it is
a rational creation capable of logical thought and self-determination. A
creature with a fixed INT (any INT listed as a single number, rather
than a die roll) is not sentient. Fixed INT creatures operate solely on
instinct rather than logic or intuition.

Attributes

The grouping gives the hit points, damage modifier and magic points of
the creature. Again, these are based upon the characteristic scores of
an average member of the species. Also listed is the creature’s movement
rate (MR), with a note if the creature can fly or swim. The profile also
gives typical armour worn, including the Armour Points (AP), as well as
the creature’s Loot Factor.

Skills

Creatures have skills like player characters. This section breaks down
into the skills categories and details the significant skills that an
average member or this species will have. Combat skills have the damage
listed, including damage modifier, and other details for the weapon
used, in brackets next to the weapons name. Unless otherwise noted, a
creature with multiple attack forms will only get to use one as its
combat action.

Magic

This section gives suggestions of the type of magic spells that an
average member of the species will know.

Special Rules

This section has details of other rules that apply to the creature. Its
abilities are described where necessary.

Creature Descriptions

== Basilisk

*_Characteristics_*

[width="100%",cols="21%,17%,11%,12%,11%,17%,11%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D3 |2D6+6 |2D6 |1D3 |3 |1D6+12 |3
|4 |13 |7 |2 |3 |16 |3
|===

*_Attributes_*

[width="100%",cols="18%,19%,15%,11%,24%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|8 |-1D6 |16 |15m |Scales (2pt) |5
|===

*_Skills_*

Resistances: Dodge 30%, Persistence 50%, Resilience 70%.

Practical: Athletics 60%, Deception 40%.

Knowledge: Natural lore 40%.

*_Combat_*

Ranged Combat 100%: Gaze (Death, 1 CR, Range: POW in metres).

Unarmed Combat 30%: Bite (1D6–1D6+poison).

Note: The basilisk can attack with both gaze and bite simultaneously in
the same action.

*_Magic_*

Basilisks do not learn magic.

*_Special Rules_*

_Corrosive Blood_: Any non-magical weapon hitting the basilisk corrodes
in the creature’s blood, completely disintegrating after 1D4 rounds.

The basilisk’s poison and corrosive blood are magical effects, which
lose their special properties a few minutes after leaving the basilisk’s
body, making it virtually impossible to use the creature as a source for
making lethal compounds.

_Basilisk Venom_

Type: Ingested or smeared.

Delay: Immediate.

Potency: 65.

Full Effect: 1D4 Hit Point damage, applies –6 penalty to victim’s CON.

Duration: 6D10 minutes.

_Death Gaze_: A basilisk can kill with a glance. In combat, the basilisk
glares at a single opponent each round. If the basilisk overcomes the
target in an opposed test of its Persistence against the target’s
Resilience, the target dies instantly. Using the gaze attack costs no
magic points, and the basilisk may normally attack in any round in which
it uses the gaze attack. This attack penetrates magical defences as if
it were a Magnitude 6 Personal Magic spell. If the target successfully
resists the gaze attack, they are unharmed, though they may be targeted
again.

== Bloodweed

Fast-moving and agile, they either charge up to their victims or creep
up using plant overgrowth as cover (+25 to Deception if plant cover is
available).

*_Characteristics_*

[width="100%",cols="20%,16%,14%,15%,10%,14%,11%",]
|===
|STR |DEX |CON |SIZ |INT |POW |CHA
|2D6+6 |3D6+6 |3D6+6 |3D6+6 |5 |3D6 |0
|13 |17 |17 |17 |5 |11 |0
|===

*_Attributes_*

[width="100%",cols="20%,20%,16%,12%,19%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|17 |+1D4 |11 |20m |Tough ‘bark’ +
(4AP) |0
|===

*_Skills_*

Resistances: Dodge 90%, Persistence 80%, Resilience 90%.

Practical: Athletics 90%, Deception 90%, Perception 35%.

*_Combat_*

Unarmed Combat 90%: Grapple, then inflict pain (Choke attack),
Bloodsucking bite (1D4 +1D4+ 1D6 Magic Point drain).

*_Special Rules_*

Bloodsucking bite, the bloodweed’s bite causes blood loss which also
drains 1D6 Magic Points.

== Beastling 

*_Characteristics_*

[width="99%",cols="17%,15%,12%,15%,14%,14%,13%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6+6 |1D6+12 |3D6 |1D6+12 |2D6+6 |3D6 |2D6
|13 |16 |11 |16 |13 |11 |7
|===

*_Attributes_*

[width="100%",cols="19%,20%,15%,11%,22%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|16 |+1D4 |11 |15m |Leather (AP 2) |2
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 30%, Resilience 30%.

Knowledge: Natural Lore 70%.

Practical: Deception 40%.

*_Combat_*

Close Combat 50%: Club (1D6+1D4), Short spear (1D6+1D4), Target Shield
(1D6+1D4).

Ranged Combat 50%: Sling (1D6+1D4, 1 CR, 50m).

Unarmed Combat 60%: Head Butt (1D6+1D4).

*_Magic_*

Beastlings are usually members of a Nature religion.

_Initiate of the Earth Mother_

Personal Magic 33%: Heal 2, Protection 2.

Divine Magic: Berserk.

== Centaur 

*_Characteristics_*

[width="100%",cols="18%,13%,14%,15%,15%,12%,13%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+6 |3D6 |3D6+3 |4D6+12 |2D6+6 |3D6 |3D6
|17 |11 |14 |26 |13 |11 |11
|===

*_Attributes_*

[width="100%",cols="20%,21%,15%,11%,20%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|19 |+1D6 |11 |20m |Leather (AP 2) |2
|===

*_Skills_*

Resistances: Dodge 30%, Persistence 45%, Resilience 60%.

Knowledge: Natural lore 60%.

Practical: Athletics 60%, Performance 50%, Deception 30%, Perception
40%.

*_Combat_*

Ranged Combat 70%: Long Bow (2D8+1D6, 1 CR, 150m).

Close Combat 40%: Lance (1D10+1D6), Target Shield (1D6+1D6 , War Sword
(1D8+1D6).

Unarmed Combat 40%: Kick (1D6+1D6).

*_Magic_*

Centaurs are usually members of Earth and Nature religion and learn
Personal Magic and Divine Magic from these.

_Initiate of the Earth Mother_

Personal Magic 40%: Heal 4, Protection 2.

Divine Magic: Berserk.

== Chreker

*_Characteristics_*

[width="99%",cols="14%,17%,16%,15%,12%,14%,12%",]
|===
|STR |DEX |CON |SIZ |INT |POW |CHA
|2D6 |4D6+6 |2D6+3 |2D6+3 |3D6 |3D6 |2D6
|7 |20 |10 |10 |11 |11 |7
|===

*_Attributes_*

[width="100%",cols="21%,20%,16%,11%,19%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|10 |0 |11 |20m Fly |None |0
|===

*_Skills_*

Resistances: Dodge 85%, Persistence 50%, Resilience 50%.

Practical: Athletics 90%, Deception 90%, Perception 50%.

*_Combat_*

Unarmed Combat 50%: Claws (1D4).

*_Magic_*

Normally none, but a chreker who is valued by its master may be taught
1D6+3 magnitude of Personal Magic.

== Dragon

*_Characteristics_*

[width="100%",cols="15%,13%,13%,20%,11%,15%,13%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|20D6 |10D6 |4D6 |10D6+30 |6D6 |4D6+12 |6D6
|70 |35 |14 |65 |21 |26 |21
|===

*_Attributes_*

[width="100%",cols="15%,16%,13%,21%,14%,21%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot

|50 |+7D6 |26 |30m on land, 45m when flying |Dragon Scales (AP 12) |5 or
6 depending on the size of the Dragon.
|===

*_Skills_*

Resistances: Dodge 30%, Persistence 100%, Resilience 100%.

Knowledge: Natural lore 100%, Culture (local) 100%.

Practical: Athletics 100%, Influence 100%, Perception 100%.

*_Combat_*

Unarmed Combat 100%: Bite (1D10+7D6), Claw (1D8+7D6), Tail (1D20+7D6).

A dragon can make either a single tail attack or two claw attacks or one
bite attack in a single Combat Round.

*_Magic_*

Dragons are highly magical creatures and often learn sorcery or Personal
Magic.

Here’s an example of magic for a wild dragon:

Personal Magic 85%: Befuddle [2], Beast Call [2], Heal 6, Protection 5,
Second Sight [3], Talk to Animals [3], Tongues [2].

Here’s an example of magic for a more civilized dragon:

Sorcery 85%: Damage Boosting, Damage Resistance, Dominate Human, Shape
change Dragon to Human, Mystic Vision.

*_Special Rules_*

_Breathe Flame:_ The dragon may breathe flame over an area as a Combat
Action. The flame will cover a cone in front of the dragon, which
stretches for its POW in metres. At its furthest extent, the cone is
equal to the creature’s POW in width.

Any creature caught in the flame suffers 4D6 fire damage, though on a
successful Dodge roll a character may dive for cover to halve this
damage and AP counts as normal.

The dragon may only breathe flame once per hour. Further attempts to
breathe flame within this time period require the creature to make a
Resilience test, with a cumulative –20% penalty for every attempt.

== Dwarf 

*_Characteristics_*

[width="100%",cols="15%,17%,12%,14%,16%,14%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6 |2D6+12 |3D6 |1D6+6 |2D6+6 |3D6 |3D6
|14 |19 |11 |10 |13 |11 |11
|===

*_Attributes_*

[width="100%",cols="16%,19%,16%,13%,23%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|15 |0 |11 |15m |Chainmail (AP 5) |3
|===

*_Skills_*

Resistances: Dodge 20%, Persistence 40%, Resilience 55%.

Knowledge: Craft 70%.

Practical: Athletics 50%, Engineering 35%, Mechanisms 40%.

*_Combat_*

Close Combat 65%: War Hammer (1D8), Battleaxe (1D6), Target Shield
(1D6).

Ranged Combat 45%: Light Crossbow (1D8,1/2 CR, 125m).

Unarmed Combat 35%: Fist/Kick (1D4).

*_Magic_*

Dwarves practice sorcery through their own Schools of Sorcery

_Apprentice Sorcerer_

Sorcery 40%: Damage Resistance, Damage Boosting, Heal Wounds.

*_Special Rules_*

_Earth Sense._ Dwarves can automatically sense how deep they are
underground and whether or not the tunnels or chambers they are in are
structurally sound.

_Dark Sight._ Dwarves see in the dark as if it is the day.

== Duck

*_Characteristics_*

[width="100%",cols="18%,14%,12%,14%,14%,14%,14%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6+3 |2D6+6 |2D6+6 |1D6+6 |2D6+6 |3D6 |2D6
|10 |13 |13 |9 |13 |10 |7
|===

*_Attributes_*

[width="100%",cols="21%,20%,17%,11%,18%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |0 |10 |10m |Leather (AP 2) |2
|===

*_Skills_*

Resistances: Dodge 60%, Persistence 50%, Resilience 50%.

Knowledge: Natural Lore 70%.

Practical: Athletics: 40%* Deception 50%, Perception 40%, Sailing 50%.

*_Combat_*

Close Combat 50%: Short Sword (1D6), Buckler (1D4).

Ranged Combat 60%: Sling (1D6, 1 CR, 50m).

*_Magic_*

Ducks usually worship a River Deity who protects their home settlements.

_Initiate of the River Deity_

Personal Magic 30%: Weapon Enhance, Walk on Water, Water Breathe.

Divine Magic: Call Small Undine 1

*_Special Rules_*

Ducks are masters of swimming, which is normally measured by the
Athletics skill, is considered to be at 100% for any skill test.

== Elf 

*_Characteristics_*

[width="100%",cols="16%,12%,15%,15%,15%,15%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6+3 |3D6 |3D6+6 |2D6+3 |3D6+6 |2D6+6 |3D6
|10 |11 |17 |10 |17 |13 |11
|===

*_Attributes_*

[width="100%",cols="20%,19%,17%,11%,19%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |0 |13 |15m |Leather (2AP) |1
|===

*_Skills_*

Resistances: Dodge 55%, Persistence 55%, Resilience 20%.

Knowledge: Natural lore 80%.

Practical: Athletics 55%, Deception 55%, Perception 30%, Healing 50% .

*_Combat_*

Close Combat 60%: Long spear (1D8).

Ranged Combat 80%: Short Bow (1D8, 1 CR, 75m).

*_Magic_*

Elves are usually at least Initiates in an Earth or similar nature-based
religion. Their leaders tend to be Priests in such religions.

_Initiate of the Earth Mother_

Personal Magic 40%: Heal 5, Multi-missile 4, Protection 3, Weapon
Enhance 3

== Elemental

The only characteristic that an elemental has is SIZ; all of its derived
attributes and skills are based on this.

*_Elemental Scores_*

[width="100%",cols="16%,6%,10%,9%,10%,9%,6%,9%,13%,12%",]
|===
|Size of Elemental |SIZ |Damage |Hit Points (=SIZ) |Attack (=SIZ x 5)
|Area of attack (=SIZ /3) |MR |Dodge |Persistence |Resilience*

|Small |3 |1D6 |3 |25% |1m |15m |100 |30 |100

|Medium |9 |2D6 |9 |45% |3m |20m |90 |60 |100

|Large |21 |3D6 |21 |80% |7m |30m |60 |80 |100

|Huge |50 |4D6 |50 |100% |16m |45m |30 |100 |100
|===

Elementals attack by engulfing their enemies. All opponents within the
area of attack are potential targets. Elementals use their Attack
percentage, which is equal to their size times five, to hit the target,
who then resists using the resistance appropriate to the attack.

*Elementals are immune to disease and poison.

[width="100%",cols="27%,18%,29%,26%",]
|===
|Elemental |Type of attack |Resistance used |Attribute damage
|Undines |Drown |Resilience |Hit Points
|Shade |Fear |Persistence |Magic Points
|Salamander |Burning |Resilience |Hit Points
|Gnome |Crush |Resilience |Hit Points
|Sylph |Bluster |Resilience |Hit Points
|===

Shades attack using Fear. When they reduce their opponent’s Magic
Point’s total to zero, they literally die of shock.

*_Other Elemental Abilities_*

*See invisible:* Elementals have magical senses that allow them to ‘see’
invisible creatures, such as immaterial spirits. They also gain a +50%
when detecting hidden characters.

*Almost invisible against the same element:* All elementals have the
equivalent of a 90% Deception when lying next to an environment of the
same element as themselves. For example, undines are nearly invisible
when lying in a pool of water and gnomes can curl up and blend into a
surrounding rocky area.

== Gargoyle

*_Characteristics_*

[width="99%",cols="20%,13%,13%,13%,13%,13%,15%",]
|===
|STR |CON |DEX |SIZ |INT |CHA |POW
|5D6+12 |3D6 |3D6 |5D6 |1D6 |1D6 |3D6
|29 |11 |11 |17 |4 |4 |11
|===

*_Attributes_*

[width="100%",cols="19%,19%,17%,16%,18%,11%",]
|===
|Hit Points |Damage Modifier |Magic Points 11 |MR |Armour |Loot
|14 |+2D6 |11 |15m, 20m flying if have wings |Tough Hide (AP 6) |0
|===

*_Skills_*

Resistances: Dodge 25%, Persistence 40%, Resilience 40%.

Knowledge: Natural Lore 40%.

Practical: Athletics 40%, Deception 30%, Perception 40%.

*_Combat_*

Unarmed Combat 50%: Claw (1D6+2D6).

*_Magic_*

Gargoyles do not learn magic.

*_Special Rules_*

Statue-Like Stillness. The Gargoyle has a 50% modifier when using
Deception to appear like a statue upon inspection.

== Ghoul

*_Characteristics_*

[width="100%",cols="22%,13%,12%,15%,14%,11%,13%",]
|===
|STR |CON |DEX |SIZ |POW |INT |CHA
|4D6 |3D6 |3D6 |2D6+6 |3D6 |3D6 |1D6
|14 |11 |11 |13 |11 |11 |4
|===

*_Attributes_*

[width="99%",cols="22%,19%,17%,12%,17%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|12 |+1D4 |11 |15m |None |1
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 30%, Resilience 40%.

Knowledge: Lore (Undead) 75%.

Practical: Athletics 40%, Deception 60%, Perception 30%.

*_Combat_*

Ranged Combat special see below: Howl (see Demoralise below).

Unarmed Combat 60%: Claw (1D4+1D4), Bite (1D6+1D4+poison).

A ghoul is able to use its howl once per combat round, in addition to
either a Claw or Bite attack.

*_Magic_*

Ghouls learn Personal Magic from each-other, with the occasional
powerful leader becoming a shaman or priest of some evil cannibal
religion.

Personal Magic 40%: Sap Energy, Scare.

*_Special Rules_*

_Ghoul Venom_

Type: Ingested or smeared.

Delay: 1D3 Combat Rounds.

Potency: 22.

Full Effect: Paralysis.

Duration: 1D10 hours or until healing is administered that restores at
least 1 Hit Point.

_Ghoul Howl:_ Ghouls employ a blood-chilling howl in combat. When a
ghoul howls, every creature in a radius equal to the ghoul’s POW in
metres becomes Demoralised (as the Personal Magic spell). This costs the
ghoul no magic points and does not require a skill test to use
successfully.

== Giant

The following Characteristics are for a giant that stands six metres
tall. For every additional two metres of height, a giant rolls an
additional 3D6+6 for STR, 2D6+6 for CON and 3D6+6 for SIZ.

*_Characteristics_*

[width="100%",cols="17%,14%,12%,14%,12%,12%,19%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|9D6+18 |6D6+18 |2D6+3 |9D6+18 |3D6 |3D6 |2D6
|49 |39 |10 |49 |11 |11 |7
|===

*_Attributes_*

[width="100%",cols="20%,21%,16%,11%,19%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|44 |+5D6 |11 |30m |Tough Hide +
(AP 3) |4
|===

*_Skills_*

Resistances: Dodge 10%, Persistence 25%, Resilience 80%.

Knowledge: Natural lore 20%.

Practical: Athletics 50%, Deception 5%, Perception 40%.

*_Combat_*

Close Combat 90%: Huge Club (2D6+5D6)

Giants tend to use mighty clubs (and sometimes even tree trunks that do
3d6 damage + damage modifier) in battle.

Ranged Combat 35%: Thrown Boulder (2D6+5D6, 1CR, 100m).

Unarmed Combat 75%: Stomp (1D6+5D6).

*_Magic_*

Giants tend to learn the magic of those Cultures nearest them. Giants
who are isolated in the mountains learn Personal Magic, with more
powerful individuals becoming Shamans. There is also the mysterious
Builder Religion that some more intelligent members of the species
belong to.

_Initiate of the Builder Religion_

Personal Magic Casting 33%: Weapon Enhance 3, Strength 5.

Divine Magic: Quicksand, Repair and Replace.

== Goblin

*_Characteristics_*

[width="100%",cols="17%,16%,11%,11%,12%,15%,18%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6+3 |2D6+3 |5D6 |2D6 |3D6 |2D6+3 |2D6
|10 |10 |17 |7 |11 |10 |7
|===

*_Attributes_*

[width="100%",cols="19%,19%,18%,11%,18%,15%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|9 |0 |10 |15m |Leather (2 AP) |1
|===

*_Skills_*

Resistances: Dodge 50%, Persistence 20%, Resilience 35%.

Knowledge: Natural lore 50%.

Practical: Athletics 50%, Perception 35%, Deception 75%, Mechanisms 50%.

*_Combat_*

Close Combat 40%: Short spear (1D6), Buckler (1D4).

Ranged Combat 50%: Sling (1D6, 1 CR, 50m).

*_Magic_*

None normally.

*_Special Rules_*

Night Sight. Goblins can see at night as if it was day.

== Gorgon

*_Characteristics_*

[width="100%",cols="17%,14%,14%,14%,12%,17%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6 |3D6+6 |3D6+6 |4D6 |3D6 |1D6+12 |1D6
|14 |17 |17 |14 |11 |16 |4
|===

*_Attributes_*

[width="100%",cols="17%,16%,13%,20%,16%,18%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|16 |+1D4 |16 |15m on land, 20m when flying |Scales (AP 8) |5
|===

*_Skills_*

Resistances: Dodge 50%, Persistence 35%, Resilience 45%.

Knowledge: N/A.

Practical: Athletics 65%, Deception 60%, Perception 50%.

*_Combat_*

Ranged Combat Special see below: Gaze attack (Petrification).

Unarmed Combat 75%: Talons (1D6+1D4), Serpent hair (1D4+poison).

Gorgons attack using their gaze at the beginning of the combat round
(see below) and then have one combat attack (either Talon or Serpents)
as usual.

*_Magic_*

Gorgons have at least 10 magnitude of Personal Magic or Sorcery or
Divine Magic. They are usually Priestesses or Adepts, with a casting
skill of 75%.

_Priestess of the Serpent Religion_

Personal Magic 75%: Weapon Enhance 4, Heal 5.

Divine Magic: Absorption 3, Fear, Heal Body.

*_Special Rules_*

_Petrifying Gaze Attack._ The Gorgon’s gaze attack is an automatic
attack at the beginning of every round. Every susceptible creature must
make an opposed Resilience test against the Gorgon’s Persistence or be
turned to stone.

_Gorgon Serpent Venom_

Type: Ingested or smeared.

Delay: 1D3 Combat Rounds.

Potency: 34.

Full Effect: 1D3 Hit Point damage, applies –3 penalty to victim’s CON.

Duration: 6D10 minutes.

== Griffin 

*_Characteristics_*

[width="100%",cols="14%,18%,17%,12%,7%,15%,17%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|8D6 |3D6+12 |3D6+12 |8D6 |6 |2D6+6 |7
|28 |22 |22 |28 |6 |13 |7
|===

*_Attributes_*

[width="100%",cols="19%,19%,15%,14%,19%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|25 |+2D6 |13 |20m on land, 30m when flying |Tough Hide (AP 3) |0
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 80%, Resilience 70%.

Knowledge: Natural lore 60%.

Practical: Athletics 80%, Deception 30%, Perception 50%.

*_Combat_*

Unarmed Combat 70%: Bite (1D8+2D6), Claw (1D6+2D6).

== Hippogriff 

*_Characteristics_*

[width="100%",cols="20%,13%,13%,15%,9%,15%,15%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6+24 |3D6+6 |3D6+6 |4D6+18 |7 |2D6+6 |5
|38 |17 |17 |32 |7 |13 |5
|===

*_Attributes_*

[width="100%",cols="17%,15%,13%,27%,15%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|25 |+3D6 |13 |20m on land, 37m when flying |Hide +
(1 AP) |0
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 40%, Resilience 50%.

Knowledge: Natural lore 60%.

Practical: Athletics 50%, Deception 10%, Perception 60%.

*_Combat_*

Unarmed Combat 60%: Fore claw (2D6 +3D6), Bite (1D8 +3D6).

== Lizardman 

*_Characteristics_*

[width="99%",cols="18%,11%,15%,17%,15%,12%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+6 |3D6 |2D6+3 |3D6 |2D6+6 |3D6 |2D6
|17 |11 |10 |11 |13 |11 |7
|===

*_Attributes_*

[width="100%",cols="19%,22%,17%,11%,19%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |+1D4 |11 |15m |Scales +
(2 AP) |3
|===

*_Skills_*

Resistances: Dodge 45% Persistence 25% Resilience 30%.

Knowledge: Natural lore 45%.

Practical: Athletics 45%, Deception 35%, Perception 35%.

*_Combat_*

Close Combat 45%: Battleaxe (1D8+1D4).

Ranged Combat 35%: Sling (1D6+1D4, 1 CR, 50m).

Unarmed Combat 25%: Bite (1D6+1D4).

*_Magic_*

_Initiate of the Crocodile God_

Personal Magic 33%: Heal 2, Weapon Enhance 2.

== Merpeople

*_Characteristics_*

[width="100%",cols="19%,12%,15%,15%,12%,12%,15%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+3 |3D6 |2D6+6 |3D6+6 |3D6 |3D6 |3D6
|14 |11 |13 |17 |11 |11 |11
|===

*_Attributes_*

[width="100%",cols="17%,18%,15%,22%,16%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|14 |+1D6 |11 |20m Swimming, 7m on land as it crawls along. |None |1
|===

*_Skills_*

Resistances: Dodge 30%, Persistence 30%, Resilience 30%.

Knowledge: Natural Lore 80%.

Practical: Athletics 60%, Deception 30%, Perception 50%.

*_Combat_*

Close Combat 35%: Long spear (1D8+1D6), Dagger (1D4+1+1D6).

*_Magic_*

Merpeople typically join the religion of the Sea Goddess.

_Initiate of the Sea Goddess_

Personal Magic 33%: Beast Call [2], Weapon Enhance 3

Divine Magic: Call Small Undine 1

*_Special Rules_*

Merpeople can breathe underwater as well as in the air when they
surface.

== Manticore

*_Characteristics_*

[width="100%",cols="16%,16%,13%,15%,10%,13%,17%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6+12 |4D6+6 |3D6 |4D6+12 |3D6 |3D6 |7
|26 |20 |11 |26 |11 |11 |7
|===

*_Attributes_*

[width="99%",cols="19%,19%,16%,13%,18%,15%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|23 |+2D6 |11 |20m |Hide(1 AP) |4
|===

*_Skills_*

Resistances: Dodge 25%, Persistence 65%, Resilience 45%.

Practical: Athletics 25%, Deception 50%, Perception 60%.

*_Combat_*

Unarmed Combat 75%: Claw (1D6+2D6), Gore (1D8+2D6), Poison Sting
(1D6+2D6+poison).

*_Magic_*

Only if someone has been stupid enough to teach it some.

*_Special Rules_*

_Manticore poison._

Type: Ingested.

Delay: 1D3 Combat Rounds.

Potency: 50.

Full Effect: 1D4 Hit Point damage, applies –3 penalty to victim’s CON.

Duration: 5D10 minutes.

== Minotaur

*_Characteristics_*

[width="100%",cols="21%,16%,11%,16%,11%,11%,14%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+12 |1D6+12 |3D6 |3D6+12 |2D6 |3D6 |2D6
|23 |16 |11 |23 |7 |11 |7
|===

*_Attributes_*

[width="100%",cols="19%,19%,18%,13%,17%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|20 |+2D6 |11 |20m |Tough hide (3AP) |3
|===

*_Skills_*

Resistances: Dodge 60%, Persistence 40%, Resilience 75%.

Knowledge: Natural Lore 65%.

Practical: Athletics 60%, Deception 10%, Perception 40%.

*_Combat_*

Close Combat 60%: Great Axe (2D8+2D6).

Unarmed Combat 60%: Gore (1D6+2D6), Head Butt (1D6+2D6).

*_Magic_*

Minotaurs tend to join Earth or Nature religions and learn Battle and
Divine magic from them.

_Initiate of the Bull Lord_

Personal Magic Casting 33%: Beast Call [2], Fanaticism [2].

Divine Magic: Berserk.

== Mummy

*_Characteristics_*

[width="100%",cols="19%,15%,12%,12%,15%,12%,15%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+12 |3D6+12 |2D6 |2D6+6 |2D6+6 |0 |1
|23 |23 |7 |13 |13 |0 |1
|===

*_Attributes_*

[width="99%",cols="20%,20%,17%,12%,19%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|18 |+1D6 |0 (See below) |15m |Tough Skin (2AP) |4
|===

*_Skills_*

Resistances: Dodge 30%, Persistence 80% (+immune to mind control magic),
Resilience 50% (+ mummies are immune to natural Disease and Poison).

Knowledge: Lore (Undead) 65%.

Practical: Athletics 10%, Deception 10%, Perception 40%.

*_Combat_*

Close Combat 80%: War Maul (2D8+1D6).

Unarmed Combat 60%: Fist (1D6+1D6).

*_Magic_*

Since mummies are POW-less, they never have Personal Magic. Mummies who
were priests in their previous lives may have Divine Magic, and mummies
who know sorcery will always know at least one Tap spell to gain Magic
Points to fuel their spells.

_Undead Sorcerer_. Sorcery Casting 75%: Tap POW, Mirage, Neutralise
Magic, Venom.

*_Special Rules_*

An Ignite spell will work on a mummy’s body. A strike with a fiery
weapon, such as a sword with a Fireblade spell on it, or even a torch,
will ignite the mummy if the hit causes damage. The damage done by the
initial hit is taken each combat round as fire damage unless the fire is
put out. To put out a fire, the mummy must take one combat round to roll
on the ground or immerse itself in water. During this time, it may not
make any other actions or reactions.

Healing spells are ineffective on mummies, though a Repair spell will
fix any damage done (in 1D10 hit point increments).

When a creature becomes a mummy, its STR and CON are doubled. The
statistics above represent a human mummy, though any sentient creature
willing to undergo the process may become a mummy.

== Nymphs 

Killing a nymph’s physical body sends it back to the magic world to
regenerate. The nymph, if unmolested in the magic world, will form a new
body in her special place after 2D6 days, provided the place remains
intact.

=== Dryad

A dryad is a nymph of a particular area of woodland, a grove of a radius
in metres equal to twice her POW. The dryad cannot leave this territory.
If she does, her physical body disintegrates into leaves and flowers, to
reform in the magic world as above. Within a dryad’s grove is a
particular tree that they are mystically linked to; they will endure for
as long as their personal tree endures, and no longer.

A dryad can form or dissolve her body by stepping out of or into this
tree, though if a dryad’s body is destroyed, it takes her time (as for
any nymph) to form another.

*_Characteristics_*

[width="100%",cols="16%,12%,11%,15%,16%,15%,15%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6 |3D6 |4D6 |2D6+3 |3D6+6 |2D6+15 |2D6+12
|7 |11 |14 |10 |17 |22 |19
|===

*_Attributes_*

[width="100%",cols="20%,22%,16%,12%,18%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |0 |22 |15m |0 |1
|===

*_Skills_*

Resistances: Dodge 50%, Persistence 60%, Resilience 40%.

Knowledge: Natural Lore 60%.

Practical: Perception 50%, Performance 50%, Deception 50%.

*_Combat_*

Close Combat 40%: Quarterstaff (1D8).

*_Magic_*

Personal Magic 60%: Befuddle, Clear Path, Countermagic, Detect Magic,
Enhance Performance, Enhance Deception, Light

*_Special Rules_*

A dryad controls all of the plants within her grove. She can cause them
to move slowly, grow surprisingly rapidly, or blossom or bear fruit out
of season. This power cannot be used as a direct attack.

=== Hag

Hags embody darkness and shadows. Hags are associated with caves and
other dark areas seldom exposed to direct sunlight. A hag can only leave
her domain when it is night and must return there before dawn; if she
does not, her physical body is destroyed.

A hag’s body is also destroyed if she is struck by direct sunlight. A
hag may form and dissolve her body at will, although if her body is
destroyed, it takes a hag time (as for any nymph) to form another.

*_Characteristics_*

[width="100%",cols="16%,11%,12%,12%,17%,17%,15%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|6D6 |3D6 |3D6 |3D6 |2D6+12 |2D6+21 |1D6
|21 |11 |11 |11 |19 |28 |3
|===

*_Attributes_*

[width="100%",cols="20%,19%,18%,11%,18%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |+1D6 |28 |15m |0 |3
|===

*_Skills_*

Resistances: Dodge 50%, Persistence 60%, Resilience 40%.

Knowledge: Lore (Magic) 40%, Lore (Undead) 40%, Natural Lore 40%.

Practical: Perception 50%, Deception 110%.

*_Combat_*

Close Combat 55%: Claw (2D6).

*_Magic_*

Personal Magic 75%: Befuddle, Countermagic, Darkwall, Detect Magic,
Disruption, Enhance Deception, Extinguish, Hinder Perception

*_Special Rules_*

A hag can create a shade out of the darkness of her lair. Doing this
costs one magic point per point of SIZ the shade has. A hag can only
manifest one shade at a time, though if it is destroyed she can create
another.

=== Naiad

Naiads are nymphs of the water, whether a particular stream, stretch of
river, lake, swamp or, occasionally, a part of the coastline.

For every ten metres a naiad moves from her body of water, she loses a
magic point. If she reaches zero magic points, her body collapses into a
pool of water and her spirit returns to her domain. A naiad can only
regain magic points when completely submerged in water.

*_Characteristics_*

[width="100%",cols="12%,11%,12%,14%,17%,17%,17%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6 |3D6 |4D6 |2D6+3 |3D6+6 |2D6+18 |2D6+12
|14 |11 |14 |9 |17 |25 |19
|===

*_Attributes_*

[width="100%",cols="20%,20%,17%,14%,14%,15%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|10 |0 |25 |15m |0 |1
|===

*_Skills_*

Resistances: Dodge 80%, Persistence 70%, Resilience 60%.

Knowledge: Natural Lore 40%.

Practical: Perception 40%, Performance 40%, Stealth 65%.

*_Combat_*

Close Combat 40%: Shortspear (1D6).

Ranged Combat 40%: Javelin (1D6).

*_Magic_*

Personal Magic 60%: Befuddle, Countermagic, Dull Weapon, Detect Magic,
Enhance Performance, Extinguish, Heal, Protection, Slow, Water Breath

*_Special Rules_*

A naiad can transform herself into an undine. Doing this takes a round
and costs one magic point per point of SIZ the undine has. If the undine
is destroyed, the naiad is unharmed but is immediately forced back to
her own body of water.

=== Oread

An oread is a nymph associated with a particular hill, mountain, or
valley. For every ten metres an oread moves from her domain, she loses a
magic point. If she reaches zero magic points, her body turns to stone
and her spirit returns home.

*_Characteristics_*

[width="100%",cols="14%,14%,14%,14%,14%,16%,14%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6 |3D6+3 |3D6+6 |2D6+3 |3D6+3 |2D6+15 |2D6+9
|7 |12 |17 |9 |14 |22 |15
|===

*_Attributes_*

[width="100%",cols="21%,22%,17%,11%,17%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |0 |25 |15m |0 |1
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 30%, Resilience 50%.

Knowledge: Natural Lore 40%.

Practical: Perception 50%, Performance 50%, Deception 80%.

*_Combat_*

Close Combat 35%: Unarmed (1D6).

Ranged Combat 40%: Rock (1D4).

*_Magic_*

Personal Magic 70%: Countermagic, Dull Weapon, Detect Magic, Extinguish,
Pierce, Protection, Repair, Slow, Vigour, Weapon Enhance

*_Special Rules_*

An oread can transform herself into a gnome. Doing this takes a round
and costs 1 magic point per point of SIZ the gnome has. If the gnome is
destroyed, the oread is unharmed but is immediately forced back to her
own hill, mountain or valley.

== Orc

*_Characteristics_*

[width="99%",cols="13%,11%,11%,18%,13%,16%,18%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6 |3D6 |4D6 |2D6+3 |3D6 |2D6+3 |2D6
|14 |11 |14 |10 |11 |10 |7
|===

*_Attributes_*

[width="100%",cols="21%,19%,16%,13%,20%,11%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|11 |0 |10 |15m |Leather (2 AP) |2
|===

*_Skills_*

Resistances: Dodge 35%, Persistence 35%, Resilience 35%.

Knowledge: Craft 40%.

Practical: Athletics 35%, Deception 45%, Perception 45%.

*_Combat_*

Close Combat 40%: Scimitar (1D8), Target Shield (1D6).

Ranged Combat 50%: Short Bow (1D8, 1 CR, 75m).

*_Magic_*

Orcs usually worship evil or warlike deities and are members of their
cults.

They also have Night Vision so they can see in the Dark as if it was the
day.

== **Penta**ghast

*_Characteristics_*

[width="100%",cols="17%,13%,13%,13%,13%,13%,18%",]
|===
|STR |DEX |CON |SIZ |INT |POW |CHA
|3D6+6 |4D6+6 |4D6+6 |2D6+6 |6D6 |3D6+6 |3D6+6
|17 |20 |20 |13 |21 |20 |20
|===

*_Attributes_*

[width="100%",cols="17%,17%,14%,13%,25%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|17 |+1D4 |20 |15m |Fur (2 AP) + immune to non-magical damage |0
|===

*_Skills_*

Resistances: Dodge 90%, Persistence 100%, Resilience 100%.

Practical: Athletics 100%, Deception 100%.

Knowledge: Obscure Practical Jokes 100%.

*_Combat_*

Unarmed Combat 80%: Kick (1D6+1D4), Bite (1D8+1D4).

*_Special Rules_*

_Scream_. Anyone in an area of fifty meters who can hear the
Pentaghast’s scream is subject to nausea and vomiting for 1D4 rounds on
a failed Resilience roll. Once the targets have either successfully or
unsuccessfully resisted the scream, they are no longer affected by it.
Mocking laughter. Anyone who can hear the pentaghast’s terrible laughter
is subject to a Demoralize spell. The demon can laugh once every two
combat rounds.

_Create Puppet._ Once per day a pentaghast is able to create a humanoid
puppet out of dung. The puppet is guided by the pentaghast’s will. Use a
standard species template (e.g. human, dwarf, elf, orc, etc..) to
provide stats and base skills for the puppet, but use the knowledge
skills of the demon. Such puppets tend to be heavily scented with
perfume, to hide the smell of the dung, so are only detected on a
successful Perception test.

_The Gift of Tongues._ The Pentaghast is able to speak all languages and
mimic flawlessly the speech of any person it has previously heard.

_Damage Immunity._ The Pentaghast is only damaged by magic and is immune
to non-magical poisons and disease.

== Pixie

*_Characteristics_*

[width="100%",cols="16%,15%,12%,12%,14%,17%,14%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D3 |3D6 |4D6 |1D6 |3D6 |2D6+6 |3D6
|4 |11 |14 |4 |11 |13 |11
|===

*_Attributes_*

[width="100%",cols="17%,17%,13%,24%,17%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|8 |-1D6 |13 |15m, 30m when flying |None |0
|===

*_Skills_*

Resistances: Dodge 60%, Persistence 60%, Resilience 20%.

Knowledge: Natural lore 80%.

Practical: Athletics 60%, Deception 60%, Perception 60%.

*_Combat_*

Close Combat 10%: Dagger (1D4+1-1D6).

Ranged Combat 25%: Sling (1D6).

*_Magic_*

Pixies are highly magical and know at least ten magnitude points of
Personal Magic.

Personal Magic 85%: Befuddle, Babel, Demoralise, Fist of Gold, Glue

In addition they know the Divine Magic spell Mischief that they can cast
at will.

== Troll

*_Characteristics_*

[width="100%",cols="18%,15%,12%,16%,13%,13%,13%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6+12 |3D6+9 |2D6 |4D6+12 |1D6+3 |3D6 |2D6
|26 |20 |7 |26 |6 |11 |7
|===

*_Attributes_*

[width="100%",cols="19%,20%,18%,11%,18%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|23 |+2D6 |11 |23m |Tough hide (3AP) |1
|===

*_Skills_*

Resistances: Dodge 25%, Persistence 25%, Resilience 60%.

Knowledge: Nature Lore 40%.

Practical: Athletics 20%, Deception 20%, Perception 20%.

*_Combat_*

Close Combat 40%: Club (1D6+2D6).

Unarmed Combat 40%: Claw (1D6+2D6).

The troll may attack with either club or claw as its action during a
combat round, but not both.

*_Magic_*

None.

*_Special Rules_*

Trolls regenerate damage done to them quite quickly. They heal 1D6 Hit
Points per Combat Round. This regeneration will not work on damage
caused by fire.

Trolls also have Night Vision so they can see in the Dark as if it was
the day.

== Satyr

*_Characteristics_*

[width="100%",cols="15%,12%,17%,16%,16%,13%,11%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|5D6 |4D6 |3D6+6 |2D6+6 |2D6+6 |4D6 |2D6
|18 |14 |17 |13 |13 |14 |7
|===

*_Attributes_*

[width="99%",cols="18%,21%,17%,12%,19%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|14 |+1D6 |14 |15m |Leather (2 AP) |1
|===

*_Skills_*

Resistances: Dodge 35%, Persistence 50%, Resilience 50%.

Knowledge: Natural Lore 75%.

Practical: Athletics 45%, Deception 60%, Influence 75%, Perception 60%.

*_Combat_*

Close Combat 35%: Short sword (1D6+1D6).

Unarmed Combat 55%: Head Butt (1D6+1D6).

*_Magic_*

Satyrs are naturally magical and know at least five points of Personal
Magic. They also tend to join an Earth or Nature religion, or become
Wises.

== Sea Serpent 

*_Characteristics_*

[width="100%",cols="20%,17%,12%,17%,10%,12%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|8D6+30 |4D6+21 |2D6 |6D6+15 |3 |6D6 |3
|58 |35 |7 |36 |3 |21 |3
|===

*_Attributes_*

[width="100%",cols="18%,19%,16%,16%,18%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|36 |+5D6 |21 |20m swim +
0 on land |Scales (AP 5) |3
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 40%, Resilience 80%.

Practical: Athletics 60%, Deception 65%.

*_Combat_*

Unarmed Combat 60%: Bite (1D6+5D6).

*_Magic_*

Sea Serpents do not learn magic.

== Skeleton

*_Characteristics_*

[width="100%",cols="21%,14%,12%,,12%,12%,16%,13%",]
|===
|STR |CON |DEX | |SIZ |INT |POW |CHA
|2D6+6 |1D6 |3D6 |3D6 | |0 |0 |0
|13 |4 |11 |11 | |0 |0 |0
|===

*_Attributes_*

[width="99%",cols="20%,21%,16%,11%,19%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|8 |0 |0 |15m |Leather (2AP) |0
|===

*_Skills_*

Resistances: Dodge 10%, Persistence 100%, Resilience 100%.

Immune to all diseases, poisons and mind control magic.

*_Combat_*

Close Combat 35%: Sword (1D8), Medium Shield (1D6).

*_Magic_*

None.

*_Special Rules_*

Skeletons have a score of 0 for INT, POW and CHA, as they have no
intelligence, will or personalities of their own. Skeletons are also
immune to disease, fatigue, poisons and mind control magic.

A skeleton has the same MR the creature had in life but, as a skeleton,
it cannot fly or swim (if the creature had those abilities while alive).
Skeletons never suffer Fatigue.

== Slime 

*_Characteristics_*

[width="100%",cols="13%,13%,14%,14%,21%,11%,14%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|1D6 |3D6 |1D6 |6D6 |1 |3D6 |1
|4 |11 |4 |21 |1 |11 |1
|===

*_Attributes_*

[width="100%",cols="19%,20%,16%,14%,18%,13%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|16 |0 |11 |7m |None |1
|===

*_Skills_*

Resistances: Dodge 10%, Persistence 40%*, Resilience 85%.

*Immune to all mind control magic, poison and disease.

Practical: Athletics 30%, Perception 75%, Deception 75%.

*_Combat_*

Unarmed Combat 75%: Envelop (Acid damage equal to the Slime’s SIZ).

*_Magic_*

Slimes do not learn magic.

*_Special Rules_*

A slime can only be killed by fire or magic. Normal weapons merely pass
through the slime’s rancid tissue, without causing damage. Because of a
slime’s caustic nature, neither acid nor poison has any effect on it.
Non-fiery Weapon Enhance spells do no damage to a slime. Disruption and
similar spells have their normal effect.

A slime’s body retains its full acidic properties for a number of days
after death equal to the creature’s CON.

It attacks by moving next to its intended victim and attempting to
envelop them. This attack has a base 75% chance of success, though the
victim may use his Dodge skill or his Athletics skill to jump out of the
way. Using Athletics rather than Dodge incurs a –40% penalty. A slime’s
attack may not be parried – the creature will simply slide around the
parrying weapon to engulf its foe.

Every round a creature is enmeshed by a slime, that creature will take
acid damage equal to the SIZ of the Slime. Armour will protect against
this damage for the first round, after which it is dissolved by the
Slime’s acid unless it is enchanted in some way or another. A character
caught by a slime may attempt to escape by making another Dodge or
Athletics skill test.

The slime can also crawl up walls and hang from ceilings.

== Spirits

Spirits can engage in Spirit Combat with living creatures that have a
POW characteristic. If they win the combat, they possess the loser,
since spirits crave a physical body for a variety of reasons, depending
on their type. For example, disease spirits possess their victims and
riddle their bodies with foul disease. See Spirit Possession in Combat
chapter for more information.

Spirits lack a physical presence, due to lack of STR, CON and DEX.

=== Disease Spirit

*_Characteristics_*

[width="100%",cols="17%,14%,13%,10%,12%,15%,19%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|– |– |– |– |2D6 |3D6+6 |3D6
| | | | |7 |17 |11
|===

*_Attributes_*

[width="100%",cols="17%,21%,15%,14%,19%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|N/A |N/A |17 |30m |None |0
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 50%.

Knowledge: Lore (Disease) 100%, Lore (Spirit World) 40%.

Practical: Deception 30%.

Spirit Combat 50%: Spectral Claw (1D6).

*_Special Rules_*

A disease spirit is, in essence, a disease, either mundane or magical.
After covertly possessing its victim, the possessed one will be forced
to make Resilience tests to resist the effects of the disease. The
disease cannot be thrown off until the disease spirit is ousted. Also,
the spirit will nearly always choose to apply its POW as a penalty to
the possessed one’s Resilience tests.

If the possessed one dies while being possessed by a disease spirit,
there is a percentage chance equal to the spirit’s POW that they will
arise as a new disease spirit in 2D6 hours.

=== Ghost

Those that should have passed into the afterlife, but who have not found
peace, remain to haunt the living as ghosts. Jealous and mean, they seek
to do harm to the living and often will try to possess a victim to
experience the joys of living once again.

*_Characteristics_*

[width="100%",cols="16%,15%,15%,12%,12%,15%,15%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|– |– |– |– |3D6 |3D6 |3D6
|– |– |– |– |11 |11 |11
|===

*_Attributes_*

[width="100%",cols="17%,21%,15%,14%,19%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|N/A |N/A |11 |20m |None |0 or 5
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 50%, Resilience N/A.

Knowledge: Lore (Spirit World) 30%.

Practical: Deception 50%, Perception 40%.

*_Combat_*

Spirit Combat 40%: Dominant Possession (1D6).

*_Magic_*

Ghosts typically gain the ability to cast Personal Magic that helps them
as ghosts. Some may remember magic from their former lives.

Personal Magic Casting 65%: Befuddle, Demoralise, Scare 4

*_Special Rules_*

Ghosts can only be affected by magic spells which either dominate or
drive them off, or by characters who can engage in Spirit Combat.

=== Healing Spirit

The nemesis of the disease spirit, this spirit appears as a happy bright
glowing orb. They are typically summoned to help heal the sick and
wounded.

*_Characteristics_*

[width="100%",cols="16%,15%,13%,11%,14%,16%,15%",]
|===
|*STR* |*CON* |*DEX* |*SIZ* |*INT* |*POW* |*CHA*
|– |– |– |– |2D6 |4D6 |3D6
| | | | |7 |14 |11
|===

*_Attributes_*

[width="100%",cols="17%,21%,15%,14%,19%,14%",]
|===
|*Hit Points* |*Damage Modifier* |*Magic Points* |*MR* |*Armour* |*Loot*
|N/A |N/A |14 |30m |None |0
|===

*_Magic_*

Personal Magic 100%: Heal 6.

*_Skills_*

Resistances: Dodge 40%, Persistence 50%.

Knowledge: Lore (Disease) 100%, Lore (Spirit World) 60%.

Spirit Combat 50%: Spiritual Blast 1D6.

*_Special Rules_*

The natural enemy of disease spirits, a healing spirit is only capable
of entering Spirit Combat with a disease spirit already covertly
possessing a creature. If the healing spirit can bring the disease
spirit to zero Hit Points, it will force it to leave its host. The
healing spirit will then depart as well, for it cannot permanently
possess any creature.

If a healing spirit is used on an individual who is sick from a mundane
illness (rather than from a disease spirit), it will add its POW as a
percentage bonus to the individual’s chance of success on their next
Resilience test to throw off the effects of the disease.

=== Magic Spirit

Magic spirits are spirits that have mastery of one or more spells. If
bound, the holder of the spirit may use the spirit’s Magic Points for
casting spells.

Magic spirits may not initiate spirit combat but may use the spells it
knows to attack or defend itself.

They appear as a series of multi-coloured orbs, equal in number to the
number of spells they know.

*_Characteristics_*

[width="100%",cols="14%,14%,12%,10%,14%,18%,18%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|– |– |– |– |3D6 |3D6+3 |1D6
| | | | |11 |14 |4
|===

*_Attributes_*

[width="100%",cols="17%,21%,15%,14%,19%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|N/A |N/A |14 |30m |None |0
|===

*_Magic_*

A magic spirit knows 1D6 Personal Magic, Divine Magic or Sorcery spells.
These spirits will only know one spell type. For example, a magic spirit
will not have both Divine and Sorcery spells, nor may it ever learn
spells of another type. If the spirit casts Divine Magic, it must regain
the use of spent spells in the same way a priest does. If casting
Sorcery or Personal Magic, it has a casting skill equal to its POW x 5.

*_Skills_*

Resistances: Dodge 40%, Persistence 50%.

Knowledge: Lore (Spirit World) 60%.

Spirit Combat 50%: Spiritual Blast (1D6).

=== Passion Spirits (Fear, Madness, Pain)

==== *Fear Spirit*

If a fear spirit covertly possesses a host, the host becomes permanently
Demoralised (as the spell), until the spirit is cast out.

==== *Madness Spirit*

If a madness spirit succeeds in covertly possessing a victim, it will
manifest itself in daily bouts of insanity. At least once per day, the
madness spirit will attempt to cause an insane fit in its host. It
matches its Persistence against the host’s Resilience in a standard
opposed test. If the host succeeds, the madness spirit will be quiescent
for at least a number of hours equal to the host’s POW.

If the host fails, he becomes incapacitated for 1D20 hours – screaming
madly, giggling incoherently or simply becoming catatonic for the
duration of the effect. The madness spirit chooses the manner of
madness, though most are partial to a single effect. The madness spirit
will also attempt to assert itself whenever its host is in a stressful
situation. Combat is an obvious example, but these spirits also delight
in affecting their hosts in a variety of other stressful, important
situations – collapsing into a fit of mad giggling while petitioning an
unfriendly king for a boon is exactly the kind of thing madness spirits
enjoy. Note, if the stressful situation occurs during a period of forced
quiescence on the part of the spirit, it will be unable to manifest
itself.

==== *Pain Spirit*

If a pain spirit manages to possess its target covertly, the victim will
be overcome with a sudden burst of pain. From that point on, until the
spirit is cast out, the victim will always be conscious of a dull ache
in his joints or a twinge in his muscles. Whenever the host acts quickly
(as in combat) or concentrates (as in spell casting), and sometimes
purely at random intervals, he is struck by a sudden spasm of pain. This
pain reduces all the host’s skill tests by a penalty equal to the
spirit’s POW.

For example, if a pain spirit with a POW of 17 possesses a victim, that
victim loses 17% from all skill tests so long as the spirit possesses
him. If they had an Athletics skill of 90%, were attempting to climb a
cliff and rolled an 80, the test would be a failure as the pain spirit
effectively reduces their skill to 73%.

*_Characteristics_*

[width="100%",cols="14%,12%,13%,10%,19%,16%,16%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|– |– |– |– |2D6+3 |3D6+6 |4D6
| | | | |10 |17 |14
|===

*_Attributes_*

[width="100%",cols="17%,21%,15%,14%,19%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|N/A |N/A |17 |30m |None |0
|===

*_Skills_*

Spirit Combat 55%: Spectral Claw (1D6).

Resistances: Dodge 40%, Persistence 50%.

Knowledge: Lore (Spirit World) 60% .

== Unicorn

*_Characteristics_*

[width="99%",cols="18%,15%,12%,14%,13%,14%,14%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|2D6+12 |3D6+12 |3D6+3 |2D6+12 |2D6+6 |2D6+12 |3D6+6
|19 |22 |13 |19 |13 |19 |17
|===

*_Attributes_*

[width="99%",cols="20%,20%,17%,13%,18%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|21 |+1D6 |19 |30m |Hide +
(1 AP) |0
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 60%, Resilience 60%.

Knowledge: Natural Lore 40%.

Practical: Athletics 60%, Deception 30%, Perception 60%.

*_Combat_*

Unarmed Combat 60%: Horn (1D8+1D6), Kick (2D6+1D6).

*_Magic_*

Unicorns rarely learn magic.

*_Special Rule_*

A unicorn can heal wounds by touching them, exactly as the Heal 8 spell,
save that it costs the unicorn only 6 magic points and any requisite
casting tests automatically succeed.

== Vampire 

*_Characteristics_*

[width="100%",cols="18%,16%,12%,15%,14%,13%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+12 |3D6+12 |3D6 |2D6+6 |2D6+6 |0 |3D6
|23 |23 |11 |13 |13 |0 |11
|===

*_Attributes_*

[width="100%",cols="19%,19%,15%,11%,22%,14%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|18 |+1D6 |0 (see below) |15m |Chainmail (5AP) |4
|===

*_Skills_*

Resistances: Dodge 40%, Persistence 80%, Resilience 80%.

Knowledge: Culture (Local) 80%.

Practical: Athletics 50%, Deception 80%, Perception 80%.

*_Combat_*

Close Combat 50%: Longsword (1D8+1D6), Target Shield (1D6+1D6).

Unarmed Combat 60%: Bite (1D6 + Magic Point drain, see below).

*_Magic_*

Some Vampires are highly magical and will either be a priest of an
appropriate death religion or make use of sorcery. Priests will have at
least 10 points of magnitude of spells and Sorcerers will know at least
five spells

_Vampire Lord Priest_

Personal Magic Casting 75%: Darkwall, Tongues.

Divine Magic: Fear, Touch of Death.

_Vampire Lord Sorcerer_

Sorcery Casting 75%: Dominate Humans, Energy Projection (Cold), Mystic
Vision, Neutralise Magic, Venom.

*_Special rules_*

_Night vision._ Vampires can see in the dark and at night as if it were
day by sensing life energy.

_Magic Point Drain._ A vampire does not regenerate Hit Points or Magic
Points normally. Instead, they must take them from other beings by
draining their blood. On a successful bite attack, the vampire will hang
on and drain D6 Magic Points from the victim every round. Each drained
Magic Point gives the vampire one Hit Point or Magic Point (vampire’s
choice). When the Vampire drains the victim’s Magic Points to 0, the
victim falls unconscious, as normal, and the vampire can choose to carry
on draining blood, except now it’s the victim’s permanent POW that is
drained.

_Shapeshifting._ Vampires have the ability to shapeshift into mist at
will. As a single Combat Action, the vampire (and every non-living item
on his person) dissolves into a thin greenish fog, approximately the
same SIZ as they were in the flesh. As a mist, the vampire is immune to
all types of physical damage, but cannot take any action except moving
up to their MR. In mist form, a vampire moves at the same speed as they
would normally and is unaffected by strong winds. Additionally, vampires
still take damage from sunlight in mist form.

As well as the ability to transform into mist, some vampires manifest
the ability to shapeshift into wolves and bats as well. As with the mist
transformation, such changes take a Combat Action to perform.

Upon death, the vampire collapses to the ground and turns to mist at the
beginning of the next Combat Round. Before then, it can be destroyed
permanently by driving a stake through its heart (the only way to
prevent it from turning to mist) and decapitating it.

_Vampires and Sunlight._ As creatures of the night, vampires cannot
stand the touch of natural sunlight. They take one point of damage to
every hit location per round that they are exposed to the sun, though
some will risk travelling in the daylight hours by wearing layers of
clothing and a hood to cover as much of their body as possible.

_Holy symbols._ In the past, the holy icons of some religion have proved
effective against vampires. Those that focus their energies against the
undead are the most likely to be effective. It is down to the Referee to
decide what supernaturally offends any particular vampire. An elven
vampire, for example, might be repelled by symbols of nature gods,
rather than by human symbols of holiness. Any character presenting a
holy symbol to a vampire as a Combat Action matches their Persistence
against the vampire’s Resilience in an opposed check. They will receive
bonuses or penalties at the Referee’s discretion, based on the
appropriateness of the symbol being displayed. On a successful test, the
vampire loses 1D4 Hit Points (unaffected by armour or any of the
vampire’s magic) and may not attack that character or any other
character under the protection of Holy Symbol.

== Zombie 

*_Characteristics_*

[width="100%",cols="22%,12%,15%,12%,13%,14%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6+12 |1D6 |1D6+3 |3D6 |1D3 |0 |1D3
|23 |4 |7 |10 |2 |0 |2
|===

*_Attributes_*

[width="99%",cols="20%,21%,17%,10%,20%,12%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|7 |+1D6 |0 |7m |None |0
|===

*_Skills_*

Resistances: Dodge 0%, Persistence (see Special Rules below), Resilience
(see Special Rules below).

*_Combat_*

Unarmed Combat 50%: Fist (1D4+1D6).

*_Magic_*

None.

*_Special Rules_*

Zombies are immune to fatigue, disease, poisons and mind control.

== Werewolf 

This being is human by day, but when the rage takes them, or under a
full moon, they transform into a giant savage wolf. Werewolves are the
very embodiment of nature or the bane of humanity, depending on your
viewpoint.

*_Characteristics_*

[width="100%",cols="17%,12%,12%,15%,21%,12%,11%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|3D6 +
(x2 as wolf) |3D6 |3D6 |2D6+6 |2D6+6 (x0.5 as wolf) |3D6 |3D6
|11 +
(22 as wolf) |11 |11 |13 |13 +
(6 as wolf) |11 |11
|===

*_Attributes_*

[width="100%",cols="20%,1%,18%,,13%,2%,16%,18%,12%",]
|===
|Hit Points | |Damage Modifier | |Magic Points | |MR |Armour |Loot
|12 |+1D6 in wolf form | |11 | |15m as man, 30m in wolf form | |Hide +
(1 AP) |0
|===

*_Skills_*

Resistances: Dodge 60%, Persistence 60%, Resilience 60%.

Knowledge: Natural Lore 80%.

Practical: Athletics 60%, Deception 60%, Perception 60%.

*_Combat_*

Close Combat 35% (as human): Longsword (1D8).

Ranged Combat 25% (as human): Short Bow (1D8, 1 CR, 75m).

Unarmed Combat 60% (as wolf): Bite (1D8+1D4), Claw (1D6+1D4).

*_Magic_*

Werewolves either learn Personal Magic handed down from their ancestors
to their family, a grouping known as the pack, or join an Earth religion
of a particularly rough and savage nature.

_Initiate of the Wolf Lord_

Personal Magic: Beast Call [2], Fanaticism [2], Coordination 3, Healing
3.

Divine Magic: Berserk.

*_Special Rules_*

_Night Vision._ Werewolves have night vision, and at night they can see
as well as they can during the day.

_Shape-Shifting._ Werewolves can change form at will, an act that
requires a Combat Round to complete. On nights of a full moon,
werewolves have no choice but to assume beast form.

While in wolf form, werewolves are immune to most damage. Only magic,
fire or weapons made of pure silver will harm them – all other blows
simply bounce off harmlessly. If a normal sword with a Weapon Enhance 3
spell cast on it is used against a werewolf, only the three points of
damage from the spell will affect the creature; the weapon’s normal
damage, as well as the attacker’s Damage Modifier, do not count. The
werewolf’s thick skin, which grants the beast one point of armour, would
reduce the Weapon Enhance spell’s damage to two. If the entire weapon is
enchanted, such as with a Fireblade spell, the entire damage rolled will
count, though the wielder’s Damage Modifier will still be ignored.

Werewolves can be poisoned, so long as the poison can be introduced to
the creature’s body. They are living entities who require oxygen and
thus may be asphyxiated or drowned.

== Wyvern 

These giant slender green reptiles are akin to dragons but with no
forelegs and animal intelligence.

*_Characteristics_*

[width="99%",cols="19%,15%,15%,15%,12%,12%,12%",]
|===
|STR |CON |DEX |SIZ |INT |POW |CHA
|4D6+12 |2D6+12 |2D6+6 |4D6+12 |7 |3D6 |6
|26 |19 |13 |26 |7 |11 |6
|===

*_Attributes_*

[width="99%",cols="19%,20%,16%,16%,18%,11%",]
|===
|Hit Points |Damage Modifier |Magic Points |MR |Armour |Loot
|23 |+2D6 |10 |20m on land, 30m when flying |Scales +
(5 AP) |1
|===

*_Skills_*

Resistances: Dodge 50%, Persistence 35%, Resilience 50%.

Practical: Athletics 50%, Deception 10%, Perception 60%.

*_Combat_*

Unarmed Combat 60%: Bite (1D10+2D6), Sting (1D6+2D6+poison), Claw
(1D6+2D6).

*_Magic_*

None.

*_Special Rules_*

_Wyvern Sting Poison_

Type: Ingested.

Delay: 1D2 Combat Rounds.

Potency: 60.

Full Effect: 1D6 Hit Point damage, applies –4 penalty to victim’s CON.

Duration: 6D10 minutes.

The Animal List

This list describes more mundane animals. It lists domestic animals
(such as horses and cattle), as well as wild beasts. Some of the animals
are in their ‘Giant’ form, which are more threatening opponents than
their normal sized versions.

None of the animals listed here have any treasure by design. They may
have some as determined by the Referee as fits the needs of the story.
For example, a carnivore may have a few trinkets in the remains of its
previous meals.

All the animals listed here have fixed INT and therefore not sentient.
None of them knows any magic.

*Animal Poisons*

_Spider Venom_

Type: Ingested or smeared

Delay: 1D3 Combat Rounds

Potency: Spider’s CON × 3

Full Effect: 1D3 Hit Points per minute and a –6 penalty to victim’s DEX
(upon reaching 0 DEX, victim becomes paralysed)

Duration: 6D10 minutes

_Viper venom_

Type: Ingested or smeared

Delay: 1 Combat Round

Potency: 48

Full Effect: 1D4 Hit Point damage for each minute and a –6 penalty to
victim’s CON

Duration: 6D10 minutes

[width="99%",cols="16%,14%,14%,14%,14%,14%,14%",options="header",]
|===
|Animal |Giant Ant |Bear |Big Cat (Lion, Tiger, etc) |Giant Beetle
|Cattle |Giant Crab
|STR |4D6 (14) |3D6+15 (25) |3D6+12 (24) |2D6+12 (19) |4D6+6 (20)
|3D6+24 (35)

|CON |3D6+6 (17) |2D6+6 (13) |3D6 (11) |3D6+6 (17) |2D6+9 (15) |3D6+6
(17)

|DEX |2D6+6 (13) |3D6 (11) |3D6+6 (17) |2D6+6 (13) |2D6 (7) |2D6 (7)

|SIZ |2D6 (7) |3D6+15 (25) |2D6+12 (19) |3D6+6 (17) |2D6+9 (15) |3D6+24
(35)

|INT |2 |5 |5 |2 |4 |2

|POW |1D6+3 (6) |3D6 (11) |3D6 (11) |1D6+6 (9) |2D6 (7) |3D6 (11)

|CHA |5 |5 |5 |2 |4 |2

|Hit Points |12 |19 |15 |17 |15 |26

|Damage Modifier |0 |+2D6 |+1D6 |+1D6 |+1D6 |+3D6

|Move |15m |20m |20m |15m |15m |15m on land, 2 in water

|Armour type |Chitin (5AP) |Tough hide (3AP) |Hide (2AP) |Chitin (5AP)
|Hide (2AP) |Thick Shell (6AP)

|Combat |50% Bite 1D6  |60% Bite 1D8, Claw 1D6 |60% Bite 1D8, Claw 1D6
|50% Bite 1D8 |40% Charge 1D8, Trample 1D8 |50% Claw 1D10
|===

[width="100%",cols="15%,16%,13%,10%,12%,11%,12%,11%",options="header",]
|===
|Animal |Giant Crocodile |Flightless Bird |Dog |Elephant |Hawk |Giant
Hawk |Horse
|STR |5D6+12 (30) |4D6+18 (32) |2D6+6 (13) |6D6+24 (45) |1D3 (2) |6D6+21
(39) |2D6+18 (25)

|CON |3D6+12(19) |2D6+6 (13) |3D6 (11) |3D6+15 (24) |2D3 (4) |5D6+15
(33) |3D6+6 (17)

|DEX |3D6 (11) |3D6+6 (17) |2D6+6 (13) |3D6 (11) |3D6+18 (27) |3D6+9
(18) |2D6+3 (10)

|SIZ |4D6 (14) |4D6+12 (26) |1D6 (3) |6D6+30 (48) |1d2 (2) |6D6+21 (39)
|2D6+18 (25)

|INT |3 |3 |5 |6 |4 |4 |4

|POW |3D6 (11) |3D6 (11) |1D6+6 (9) |2D6+6 (13) |2D6 (7) |3D6 (11) |3D6
(11)

|CHA |3 |3 |5 |5 |4 |4 |5

|Hit Points |15 |18 |7 |36 |3 |36 |21

|Damage Modifier |+1D6 |+2D6 |0 |+5D6 |-1D6 |+4D6 |+2D6

|Move |7m on land, 2 in water |20m |20m |20m |15m, 30m Flying |20m, 30m
Flying |30m

|Armour type |Thick Hide (5AP) |Thick feathers (3AP) |None |Thick hide
(3 AP) |None |thick feathers (3 AP) |Hide (2AP)

|Combat |50% Bite 1D8 |45% Peck 1D8, Kick 1D6 |40% Bite 1D6 |45% Trample
1D12, Tusk 1D10, Trunk Grapple |50% Claw 1D6, Bite 1D4 |80% Claw 1D8,
Bite 1D6 |40% Kick 1D6
|===

[width="100%",cols="17%,11%,14%,16%,13%,15%,14%",options="header",]
|===
|Animal |Giant Lizard |Giant Octopus |Pteranodon |Giant Python
|Rhinoceros |Giant Spider
|STR |2D6+12 (19) |12D6 (42) |4D6+6 (20) |3D6+24 (35) |2D6+21 (26)
|2D6+12 (19)

|CON |3D6 (11) |4D6+6 (20) |3D6+3 (14) |3D6 (11) |3D6 (11) |3D6+6 (17)

|DEX |1D6+12 (15) |3D6+12 (23) |2D6 +12 (17) |2D6+6 (13) |2D6 (7) |2D6+9
(16)

|SIZ |2D6+12 (19) |12D6 (42) |4D6+12 (26) |3D6 (11) |2D6+21 (26) |4D6+12
(26)

|INT |3 |4 |3 |3 |3 |8

|POW |3D6 (11) |3D6 (11) |3D6 (11) |3D6 (11) |3D6 (11) |3D6 (11)

|CHA |3 |4 |3 |3 |3 |2

|Hit Points |15 |31 |20 |11 |19 |22

|Damage Modifier |+1D6 |+4D6 |+2D6 |+2D6 |+2D6 |+1D6

|Move |15m |7m land, 30m swimming |15m on land, 30m flying |15m |20m
|15m on land, 20m in web

|Armour type |Hide (2AP) |Tough skin (4 AP) |Tough hide (3 AP) |Scales
(3 AP) |Thick hide (5 AP) |Chitin (4 AP)

|Combat |25% Bite 1D6, Kick 1D8 |50% Bite 1D8, Arm 1D4 |50% Bite 1D8,
Claw 1D6 |50% Bite 1D4, Constrict 1D8 |50% Bite 1D6, Gore 1D8, Trample
1D12 |50% Bite 1D6+ Venom see below, Webbing (Entangles Athletics vs
rolled attack to escape or spiders POW x2 as Hit Points to destroy)
|===

[width="100%",cols="16%,17%,21%,18%,12%,16%",options="header",]
|===
|Animal |Triceratops |Tyrannosaurus |Velociraptor |Viper |Wolf
|STR |6D6+30 (51) |4D6+40 (52) |4D6+12 (26) |2D6+6 (13) |3D6 (11)

|CON |3D10+12 (28) |5D6+30 (47) |3D6+3 (14) |2D6 (6) |3D6+3 (14)

|DEX |2D6+3 (10) |2D6+3 (10) |4D6 (14) |3D6+18 (27) |3D6+3(13)

|SIZ |6D6+30 (48) |4D6+30 (42) |3D6+6 (17) |2D6 (7) |2D6+3 (10)

|INT |3 |3 |4 |3 |5

|POW |3D6 (11) |2D6+6 (13) |2D6+6 (13) |2D6+6 (13) |3D6 (11)

|CHA |3 |3 |3 |3 |5

|Hit Points |38 |45 |16 |7 |12

|Damage Modifier |+5D6 |+5D6 |+1D6 |0 |0

|Move |30m |30m |30m |30m |20m

|Armour type |Scales (10 AP) |Thick Hide (10 AP) |Scales (5 AP) |Scales
(1 AP) |None

|Combat |50% Tail lash 1D12, Gore 1D10 |60% Bite 1D10, Stomp 1D10 |50%
Bite 1D8, Claw 1D6, Fore claw 1D4 |60% Bite + Venom (see below) |50%
Bite 1D8, Claw 1D6
|===
