Character Generation

OpenQuest character generation is a seven-step process and, at each
step, the player makes decisions about what their character is like at
the beginning of the game, when the character is just starting on their
adventuring career.

Character Concept

A character concept is a one-sentence summing up of what the character
is all about.

*Step 1: Determine Concept*

In one sentence, sum up what your character is all about. Use the
guidelines above to give yourself ideas. Ask the other players what
their character concepts are to make sure the group has an exciting
selection of characters.

Check with your Referee that your character concept fits in with the
type of game that the group is going to be playing.

Characteristics

The characteristics are:

_Strength (STR):_ A character’s capability with brute force, strength
affects the amount of damage they deal, how much they can lift and so
on.

_Constitution (CON):_ A measure of the character’s health, constitution
affects how much damage they can sustain in combat, as well as general
resistance to disease and other illnesses.

_Dexterity (DEX):_ Dexterity is the character’s agility, coordination
and speed of reactions. This ability aids a character in many physical
actions, including combat.

_Size (SIZ): Size_ is an indication of the character’s mass and, like
strength and constitution, affects the amount of damage a character can
deal, and how well they can absorb damage.

_Intelligence (INT):_ A character’s ability to think around problems,
analyse information and memorise instructions.

_Power (POW):_ Power is a measure of the character’s life force, the
strength of their willpower, and a measure of how much magic power they
have. It is a beneficial characteristic for those interested in becoming
accomplished spellcasters.

_Charisma (CHA):_ This quantifies a character’s attractiveness and
leadership qualities.

*Step 2: Generate Characteristics*

*Using the Points Method*

Each characteristic starts with a value of 8. You have thirty points to
distribute to increase them. The maximum value of a characteristic
during character generation is 18. You may also lower a characteristic
to gain extra points. For example, reduce STR from 8 to 6 to gain 2
points. Note that INT and SIZ cannot be decreased below 8. Other
characteristics have a minimum value of 3, although such a low value
would indicate that the character has a severe disadvantage in this
area.

*Random Generation of Characteristics (Optional)*

If you prefer a more traditional method of rolling dice to create
characteristics, follow this process.

For humans.

[width="100%",cols="14%,13%,15%,17%,16%,13%,12%",]
|===
|*STR* |*DEX* |*CON* |*SIZ* |*INT* |*POW* |*CHA*
|3D6 |3D6 |3D6 |2D6+6 |2D6+6 |3D6 |3D6
|===

Attributes

Attributes are a set of secondary scores that define the character’s
potential to do and take physical damage, how quickly they move, and the
amount of magical energy available to the character. The character’s
characteristic scores determine the value of their attributes.

_Damage Modifier (DM):_ The Damage Modifier applies whenever the
character uses a melee or thrown weapon. It’s calculated by adding the
character’s Strength and Size together and referring to the table below.
The modifier gets more significant when the sum of Strength and Size are
higher –bigger, stronger, characters deal out more damage than smaller,
weaker, characters.

*_Damage Modifier_*

[width="100%",cols="50%,50%",]
|===
|*Total of STR and SIZ* |*Damage Modifier*
|1–10 |–1D6 *
|11–15 |–1D4 *
|16–25 |+0
|26–30 |+1D4
|31–45 |+1D6
|46–60 |+2D6
|61-75 |+3D6
|76-90 |+4D6
|Every additional + 15 |+1D6
|===

*If after you have taken away the rolled damage modifier and the damage
is under 0, increase it to 1.

_Hit points (HP):_ These determine how much damage the character can
sustain before reaching unconsciousness or death.

_Magic points (MP):_ A measure of the character’s magical energy. Used
to activate any spells the character knows.

_Movement rate (MR):_ This is the amount in metres that a character can
move in a five-second Combat Round.

*Step 3: Determine Attributes*

To work out your character’s damage modifier, add Strength and Size
together and look at the Damage Modifier table.

Hit points equal Size plus Constitution divided by 2, rounded up.

The character’s starting magic points will be equal to the character’s
POW.

Human characters have a Movement rate of 15 metres.

Skills

Skills are things that the character can do. They represent particular
areas of expertise. In-game, the percentage value of the skill is rolled
against, using a D100, to work out if a character completes a task in
the game. A roll equal to or less than the skill percentage indicates a
success.

For example.

Ethelred has a Dodge of 52%, which means that in combat he has to roll
52 or under on D100 to avoid the incoming blows of his opponent.

*What do the Numbers Mean?*

The following table translates the skill percentage into a ‘real world’
description of the level of expertise.

*_Skill Expertise_*

[width="100%",cols="20%,27%,53%",]
|===
|*Skill* |*Expertise* |*Description*

|0-25% |Novice |No experience with the skill and is relying on raw
talent and beginner’s luck.

|26-50% |Apprentice |This level of expertise represents someone actively
learning the skill.

|51-75% |Veteran |The character is competent with the basic uses of the
skill, which they use in everyday life.

|76-99% |Expert |This character is a local expert at the skill, who can
perform it under most conditions with ease and elegance.

|100% |Master |They are acknowledged as best at that skill, and
regularly perform the impossible in challenging conditions.
|===

100% is the upper limit for skills, either through improvement or by
being modified before a skill roll. Characters with skills at 100% are
Masters of their skills, and always automatically succeed with a
critical effect.

== Skill Lists

Skills categorised for easy reference.

_Resistances_ are skills that get the character out of harm’s way.

_Combat skills_ measure the character’s skills in physical violence.

_Knowledge skills_ measure the intellectual abilities of the character.

_Practical skills_ measure the character’s ability to perform a variety
of everyday and specialist tasks.

_Magic skills_ cover either casting magic or knowledge of religious
practices.

_A note about skills with descriptors in brackets._ Lore (Type),
Religion (Other Religion) and Culture (Other) all have a descriptor in
brackets after the main skill name

=== Skill Bases

*_Resistances_*

[width="100%",cols="53%,47%",]
|===
|Skill |Base
|Dodge |DEX+10
|Persistence |POW+10
|Resilience |CON+POW
|===

*_Combat Skills_*

[width="100%",cols="63%,37%",]
|===
|Skill |Base
|Close Combat |DEX+STR
|Ranged Combat |DEX+INT
|Unarmed Combat |DEX+STR
|===

*_Knowledge Skills_*

[width="100%",cols="60%,40%",]
|===
|Skill |Base
|Culture (Own) |INT+10
|Language (Own) |INT+50
|Natural Lore |INT+10
|Culture (Other) |INT
|Language (Other) |INT
|Lore (Type) |INT
|===

*_Practical Skills_*

[width="100%",cols="55%,45%",]
|===
|Skill |Base
|Athletics |DEX+STR
|Craft |INT+10
|Deception |DEX+INT
|Driving |DEX+INT
|Engineering |INT+10
|Healing |INT+10
|Influence |CHA +10
|Mechanisms |DEX+INT
|Perception |INT+POW
|Performance |CHA+10
|Riding |DEX+POW
|Sailing |DEX+INT
|Streetwise |CHA+POW
|Trade |INT+10
|Wealth |INT+CHA
|===

*_Magic Skills_*

[width="100%",cols="60%,40%",]
|===
|Skill |Base
|Personal Magic Casting |POW X 3
|Sorcery Casting |INT
|Religion (Own Religion) |INT+10
|Religion (Other Religion) |INT
|===

*Step 4: Calculate Skills*

For each skill, calculate the starting skill value, also known as the
base score, from the calculation provided. Then write it down on the
character sheet next to the skill.

During character generation, the player gets a pool of points to spend
on each group of skills. Distribute points between the skills, with a
limit of no more than 30 to be allocated to any one skill.

_Resistances:_ Spend 50 points between the three skills.

_Combat:_ Spend 50 points between the three skills.

_Knowledge:_ Spend 50 points between the skills.

_Practical:_ Spend 75 points between skills.

_Magic:_ is special, refer to Generating a Character Step 5 below.

Magic

*Step 5: Magic Spells*

Look at the spells in the Personal Magic chapter and pick six points of
magnitude worth. Also work out Personal Magic Casting Skill, which
starts at POW X 3.

Equipment

Each character typically starts with some money and the tools of their
trade.

*Step 6: Cash and Equipment*

* Starting cash is 4D6 x 10 in silver pieces unless you are using the
optional rules to abstract resources using the Wealth skill.
* Each character starts with one of the two arms and armour packages
below:
* Leather armour, ranged weapon, close combat 2H weapon and dagger.
* Leather armour, a medium or small shield, ranged weapon, close combat
1H weapon and dagger.
* Also, each character starts with the following equipment:
* A backpack, rope, two weeks’ worth of travelling provisions, flint and
tinder, and a waterskin.

Your Referee may allow you to buy additional equipment before the game
starts from the character’s starting cash.

Finishing Off the Character

*General Information*

_Age:_ Human characters start at any age between 18 and 28. To randomly
determine this, roll 2D6 and add 16.

_Fortune points:_ Every character starts with two fortune points.

*What are Fortune Points?*

Fortune points are what distinguishes the player character from the
average stay at home type folk. They represent their good fortune and
ability to escape life-threatening situations with ease.

Fortune points allow the player character to do any of the following in
game.

* Re-roll any failed dice roll.
* Flip the existing dice result for a failed test so that the units are
now the tens and the tens are now the units, so that it is a success.
* Avoid character death. Instead of dying, the character, if reduced to
zero or fewer hit points, is merely unconscious. The character remains
in such a state until the combat is over, at which point they awaken
with one hit point.
* If the character uses Divine Magic, they can spend fortune points
invoke their deity and regain a cast spell of their choosing.

Once spent, fortune points are gone. The Referee awards fortune at the
end of the game session for moments of outstanding heroic play.

In an average Quest, each character should also receive two fortune
points. Modify this total if the character has performed particularly
poorly or heroically, giving a range of between zero and four fortune
points to be awarded.

*Background, Appearance and Personality*

Even if you do not create a fully written-up background, it is worth
making a mental note of what the character is like as a person and
roughly what their background is previous to play, as well as
visualising what they look like.

*The Character’s Background*

The background is useful not only to give the character history before
the game starts but also as a way of noting all the intangible elements
of the character’s personality. Ethelred’s story later in this chapter
is an example of a background.

Writing down a background is optional and can be done either before or
after character generation or can even emerge during play.

*Motives*

Motives are what drives the character’s actions. They are the
character’s goals, both short and long-term.

Saga Motives are life motives and are only achievable throughout a
linked set of adventures, commonly known as a ‘campaign’ or Saga as
OpenQuest calls it.

Quest Motives are usually relevant to the adventure currently being
played and are determined near the beginning of the session by the
players.

At the end of character generation, choose one Saga Motive for your
character and at the beginning of the adventure, choose a suitable Quest
Motive.

*Step 7: Finish Off the Character*

Note down fortune points and age.

For humans, this is 18-28 (2D6+16) respectively for starter adventurers.

Fortune points starts at 2.

Create at a Saga Motive for the character

If you want to include a background narrative, then do this now.

Finally, if you haven’t done so already, write the character’s name on
the character sheet.

Non-human adventurers (Optional)

With the Referee’s permission, your character may be one of the
creatures found in the Creatures chapter.

Use the random method to determine characteristics and roll the dice.

or

Take the value in brackets as the starting point and add ten points
amongst them. Characteristics cannot be increased above the maximum
value permitted by the random method (i.e. the maximum rollable plus
three).

Make a note of the special abilities, traits, movement rates, natural
armour and the natural weapons of the creature; damage base is as given,
and skills start at Base Value.

Then determine skills and magic as normal, perhaps using the weapons and
skills on the creature description which depict an average member of the
species as a guide.

Ready-Made Concepts

Ready-made concepts give quick ideas for players who are struggling to
decide which skills and magic to choose.

Follow the character generation process up to the section on spending
points on skills and choosing magic (steps 4 & 5). Instead of step 4 and
5, use the skill points and magic spells allocation as listed for the
concept. Roll for money as normal but write down all the suggested
equipment on the character sheet instead of the normal default
adventuring starting equipment.

Each concept has the following components:

A name. A one-sentence summary of the concept.

• Skills. A ready-made points allocation for each of the skills groups.

• Personal Magic. Non-variable spells have the magic point cost in
square brackets.

• Equipment.

So here we go here’s an example of a ready-made concept for players who
are stuck for ideas.

Adventurous and Knowledge-Hungry Scholar

Skills:

Resistances: Dodge +30, Persistence +10, Resilience +10.

Combat: Close Combat+20, Ranged Combat+10, Unarmed Combat +20.

Knowledge: Language (Other) +20, Lore (Ancient Dead Civilisations) +30.

Practical: Athletics + 25, Influence +20, Perception +30.

Personal Magic: Coordination 2, Protection 2, Second Sight [2].

Equipment: Scholar’s robes over leather armour, staff or dagger, and
sling & stones.

Character Growth

As characters go on Quests, they grow and improve. In the game, this can
be one of the tangible goals for the players.

The main currency for achieving this and indicator of how well the
character is doing in game terms are growth points or just simply
growth. The Referee hands these out after a Quest.

Growth can happen because of three situations.

* _Bringing motives into play_, as determined by the player and approved
by the Referee.
* _Quest achievement awards_. These are determined and handed out by the
Referee.
* _In game rewards for skill use._ If the player fumbles or criticals
during a skill test.
* _Ad hoc growth awards._ The Referee gives these out as a result of
certain events occurring during the Quest.

Awarding Growth for Motives

The characters’ motives are the main way players get to drive play and
grow their characters.

If your character completes a motive, either short or long term, during
a gaming session, cross it out.

If you engage with a motive in a gaming session, bringing it in to play,
but don’t complete it, put a * next to it. You can only mark growth once
in this way per Quest.

Make sure you make these marks as soon as your character achieves them
with your Referee’s permission.

At the end of the Quest, look at your motives.

+5 growth points if you complete your Saga motive.

+2 growth points if you complete your Quest motive.

+1 for every motive that is brought into play. You don’t get this award
as well as the award for completing a motive.

As a result, you should have a total between 1 growth point (you engaged
with your short-term Quest motive) and 7 growth points (you complete
both your Quest motive and Saga motive).

At this point, rub out any asterisk markers and remove any short-term
motives, whether completed or not. Leave the completed long-term motives
on the character sheet.

*Motive Review*

At the end of each Quest, the player and the Referee can call for a
Motive Review. During the review, the player can change Saga Motives
that are no longer interesting to them or relevant to the character.
They can also remove uncompleted Quest Motives or carry them over to the
next Quest, in which case the Referee makes a note of them.

Referee Growth Awards

The Referee award character growth as a result of the following.

* _Quest achievement award_ is directly linked to how long the quest
was.
* _In game rewards for skill use._ If a character fumbles or criticals
during a skill test, their player adds a growth point immediately.
* _Ad Hoc awards_ that acknowledge growth that occurs due to
achievements outside of the standard growth system.

*Quest Achievement Awards*

At the end of a Quest, the Referee makes this award, a simple flat award
of two growth points for each session of play of average length of
two-three hours. Adjust for longer sessions.

For example, A self-contained one session one-shot game that took three
hours should give two growth points, while a Quest that took four
sessions, each two to three hours, to play out gives eight growth points
to each player.

Note: if you want to reward clever or entertaining play, use fortune
points instead (see box below).

*In Game Rewards for Skill Use*

If a character fumbles or criticals during a skill-test, they grow from
the experience and the player immediately records a one-point growth
award. The table should also cheer on the player. There is no limit to
how many times this reward can be issued. The reward reflects this
author’s belief that we grow from great success or great failure.

*Ad Hoc Awards*

Ad hoc means when necessary or needed.

The characters may grow as part of the Quest in ways that are immediate
and hard to fit within the context of awarding growth points and the
Referee wants to make a one off award of a character growth directly
linked to the Quest.

For example.

* A Wise may teach (for free) the spell of Detect Gold as a reward for
completing a Quest on their behalf.

Spending Growth Points

Players may spend growth points in the downtime between Quests, even
when their characters who are badly injured are healing. The default
downtime period is three months, although it could drop to mere days if
the flow of time in the series of Quests, known as a Saga, requires it.

*Growing Skills*

A player may improve any number of skills by spending growth points, but
each skill can only go up by +5%, during the downtime between
adventures.

The cost of that growth depends on the expertise of the skill.

*_Growth Costs by Expertise_*

[width="99%",cols="34%,33%,33%",]
|===
|*Skill* |*Expertise* |*Growth cost Per +5%*
|0-25% |Novice |1
|26-50% |Apprentice |2
|51-75% |Veteran |3
|76-99% |Expert |5
|100% |Master |10 to reach 100%
|===

*Growing Characteristics*

A player can choose to spend five growth points to increase one
characteristic by one point.

SIZ never increases using growth points.

The maximum a human character can increase a characteristic to is 21.
For non-humans, the maximum for a characteristic is equal to the maximum
possible starting score for the characteristic plus three.

This type of growth allows the character to overcome the innate
weaknesses they suffer due to low characteristic scores.

*Growing Magic*

How the character learns more magic is dealt with in the respective
magic chapters (Personal Magic, Divine Magic, and Sorcery). But for
convenience the costs are summarised in the following table.

*_Summary of Growth Costs_*

[width="100%",cols="42%,58%",]
|===
|*Cost* |*Growth*

|One growth point |+5% to Skill

|Five growth points |+1 to any characteristic except SIZ

|One growth point per magnitude |Learn a Personal Magic spell

|Two growth points per magnitude |Learn a spell or an increase the
magnitude of a Divine Magic spell

|Three growth points |Learn a Sorcery Spell
|===

Improving Outside of Quests: Practice And Research

The characters may often experience long stretches of downtime between
Quests. Group members may need to heal from wounds suffered during the
last Quest, the characters may engage in some activity that takes time,
or life may return to normal until the next danger to face the player
characters appears.

During such downtime, the characters may improve their characters. The
players might request downtime between Quests to learn new skills, and
it is up to the Referee to determine if this is appropriate.

For every three months of practice or research, a character may gain one
growth point, which they can spend on growth. Note skills can only
increase by +5% per downtime period.

Improving in Magical Rank

There are growth point costs when a character increases their rank in
their religions and in sorcery, and when they become a specialist caster
using Personal Magic—explained in more detail in the relevant chapters,
along with the benefits.

Unlearning Spells and Changing Magical Path

Suppose characters change religions or even magic path. In that case,
they may want to free up previously learnt magic spells, to learn a more
powerful spell. For example, a character might change spells when they
graduate from being Personal Magic users to users of Sorcery or Divine
Magic, or learn the Divine Magic of their new religion if they change
faith.

Characters may do this during downtime between adventures. The player
describes how their character is spending time unlearning the spell and
then, as long as they have a teacher or source of the new spell, they
can learn it. Also, extra growth points from the character’s current
pool are added to the growth points freed up by unlearning the spell, to
make up the total growth points needed to learn the new spell.

Also, they may return the growth points they spent to become a
specialist caster (such as Shaman, Wise, Priest or Adept). They can then
spend this growth on spells, or more likely on becoming a specialist
caster in their new magical path.
