The Basic Skill Test

The basic skill test is the unifying rules mechanic that does everything
in OpenQuest. Roll a D100 and compare the result against a skill and
depending on the result, apply the effect of success or failure.

To make a skill test, the player first describes what their character is
doing. Then they roll a D100 and compare this to the relevant skill’s
score. If the dice roll is equal to or less than the skill’s score, the
attempt is successful. The player then describes the character’s
success. If the total is higher than the skill’s score, then it has
failed. The Referee then describes the result of the character’s
failure.

Under normal conditions, a skill test is asked for when the character is
placed on the spot and must make a successful action under pressure.

Unstressed Skill Tests

If the character has lots of time, has the tools of their trade and is
in a sufficiently relaxed environment and state of mind, they complete
the task to the best of their ability.

For example, an apprentice potter (Craft 20%) will, day in day out,
produce a couple of pots of passable quality if working at their
Master’s workshop. Of course, work beyond the skill of the character is
still out of their reach, unless the player decides to take the chance
with the dice and ask for a skill test.

A local noble wants an artistic piece of pottery for a grand celebration
later in the month. The noble’s servant comes to the potter’s workshop,
looking for the Master, who is out. The apprentice, seeing a chance to
gain a good reputation, takes the commission. Knowing that his regular
work will not be up to scratch, the player decides to roll the dice in
the chance that he can produce something of the standard the noble
expects.

If the Outcome is Hazardous

BEFORE THE SKILL TEST IS MADE, the Referee should also outline what any
potential hazards there are if the character should fail. Players should
be allowed to choose an alternative course of action. Also, the Referee
should not apply extra penalties if the skill test is failed, or even
fumbled (see below).

The Basic Skill Test Procedure

Overall, the procedure is as follows.

[arabic]
. The Referee calls for a skill test and asks the player to roll against
a specific skill to resolve the current situation.
. The player describes how their character is tackling the task at hand.
. If there are any hazards or penalties for failing the task, the
Referee should declare them, and the player should be allowed the option
to plot an alternative route for their character, which may allow them
to change the skill being used.
. If the character has any active magic from spells or items that gives
them a bonus or penalty, apply this to the skill now.
. The Referee decides if the situation modifies the difficulty of the
skill roll. Whether there is a bonus or a penalty (but not both and not
multiple modifiers) to be applied to the skill before the player rolls
the dice. See Difficulty below.
. The player rolls D100 and compares it against their skill, which may
be modified.

* If the roll is lower or equal to the skill’s value, they succeed. The
player describes how the character succeeds.
* If it is higher, they fail. The Referee describes how they fail.
* If they succeed and both dice are the same number, then the result is
a critical success.
* If they fail and both dice are the same number, then the result is a
fumble.

Success

If you roll equal to or lower than your modified skill total, you are
successful.

You can now describe what the character does as they succeed.

The character gets an automatic success if the modified skill is over
100%, but you still roll to see if you get a critical success.

*Critical Successes*

If the dice roll on a skill test is successful and both dice are the
same (i.e. ‘11’, ‘22’, ‘33’, etc.), then a critical success is achieved.

Critical success has an outcome that far exceeds the expectation of the
player. It’s the best possible result based upon what skill the
character used to perform the test.

The actual result of a critical success during a skill test is up to the
player. It usually achieves one of the following results:

* Quicker.
* The result is to a higher standard.
* With more style, impressing any audience they may have.
* The character gains additional information or insight from the task
thanks to their brilliance.
* If the character is causing damage as a result of the skill test, they
cause maximum damage and ignore any armour or protection that their
opponent may have.

The Referee can moderate the critical result, vetoing or suggesting more
reasonable outcomes if the player tries to narrate more success than is
reasonable, but the player always suggests the effect.

Failure

If the dice roll on a skill test is higher than the modified skill, then
a failure occurs. The Referee narrates the failure and its effect.

Note: The Referee should take care not to penalise the character with
multiple effects for failing. The result of failing should be
straightforward and as a direct result of the character’s actions.

If the Referee has previously outlined the risks of failure, then they
should implement that as a result. They should not suddenly change their
mind.

*Failing Forward*

Failure of a basic skill test should never stop the character from
progressing through the adventure. There should always be options and
possibilities, even when the player fails a skill test. A process which
is known as failing forward.

Here are some examples of fail forward situations.

* The characters fail to pick or force a locked door? Their efforts make
enough noise to alert a patrol of passing guards, who now come crashing
through the door ready for trouble. The characters must think fast, do
they respond with violence or make up a convincing story and fast talk
their way past the guards?
* The characters all failed their Perception skill tests to notice an
iron key hidden in a rubbish pile while searching a room earlier, and
now that they have found a locked chest. Will they break it open or get
their lock picks out?
* The group’s Sorcerer failed their Language skill test to decipher an
ancient text about an ancient Demon they are about to face. The
adventurers still face the horror, but they do not know its weaknesses
or the spell that the scroll outlined.

Failure should not be a barrier to resolving the adventure but instead
should open interesting difficulties to resolve.

*Fumbles*

Whenever a skill test results in failure and both rolled dice are the
same number, the character has ‘fumbled’ the test.

A fumble is the worst possible outcome of the skill test based upon the
player’s original description of what their character was planning to
do.

The actual result of a fumble is primarily up to the Referee to decide.
It usually results in one of the following mishaps.

A fumble need not lead to damage and the demise of the character, but
should always cause the character to suffer a significant disadvantage.

*Fumbling Forward?*

Unlike a simple failure, fumbling should be a dead end to play, to
emphasise how bad things are. All the character can do is dust
themselves off and take another route to success.

There are specific Critical Success and Fumble results for weapon skill
tests in combat and magical casting skill tests, described in the
relevant chapters (Combat and Magic).

Difficulty

If the conditions and situation are different from those usual, the
Referee may modify the skill to reflect the difference in difficulty.
Modifiers are added or subtracted from the skill for the duration of the
test. A penalty will make the test harder while a bonus makes it easier.
Only one modifier is used during a test. (See When a Referee Should
Apply Difficulty Modifiers below for guidance on this.)

*_Difficulty Modifiers_*

[width="100%",cols="28%,20%,52%",]
|===
|*Difficulty* |*Skill Modifier* |*What the modifier means*

|Easy |+50% |The character should have an almost certain chance of
success.

|Simple |+20% |While success is still by no means certain, the character
has a boost to their chance of achieving their goal.

|Normal |+0% |The skill is unmodified since normal conditions apply.

|Difficult |–20% |Significantly hindered in their chance of success.

|Hard |–50% |Suffering a severe setback that may put success beyond
their reach.
|===

Impossible Success And Automatic Failure

Any skill modified to 0 or less will automatically fail when tested.
Roll dice anyway since the character can still fumble.

Any skill modified to 100% or higher will almost always automatically
succeed when tested. Roll the dice anyway since the character can be
still make a critical success or fumble if the player rolls a 00. This
rule of 00 being an automatic fumble does not apply to a character who
is a Master of the skill.

When the Referee Should Apply Difficulty Modifiers

Modifiers should only be applied when they have a significant effect on
the character’s chance of success. They should not be doled out for
every skill test since this cheapens their dramatic impact. Only apply a
modifier when it is essential and brings something to the story. Resist
the urge to hand out +10% here and take -5% there. These little
modifiers do not add much to the player’s chance of success and bring
needless fiddly addition and subtraction into play.

There are three areas where the Referee should modify the player’s skill
before a skill test. The Referee should consider all three areas and
decide which of them provides the deciding factor, and only apply the
modifier based on that.

For example, if the player has roleplayed his character to the hilt
while influencing a guardsman in the pouring rain, it is the roleplaying
for which the Referee awards a +50% bonus and not the rain, which would
have dampened the enthusiasm of the guardsman to -20%. So, only +50%
applies to the player’s roll.

The three areas are:

* As a result of the task being inherently easy or difficult.
* As a result of planning.
* As a result of good roleplaying.

*As a Result of the Task Being Inherently Easy or Difficult*

Some things are just naturally easier or harder to do than others.

For example, climbing a cliff with natural handholds and with the proper
equipment (e.g. ropes and iron spikes) is an unmodified task. Doing the
same climb in the pouring rain makes it Difficult (-20% to the skill)
and if the character has also forgotten his ropes and spikes, then this
makes it Hard (-50% to the skill).

In comparison, climbing a cliff where there are numerous ledges, and
where the character can rest and actually ‘walk’ up the cliff in places
becomes an Easy (+50%) skill test.

*As a Result of Planning*

The players have outlined how their characters prepare to perform a task
well in advance. If their plan is a sound and good one, you should make
the skill test Easy. Conversely, if the players have given no thought as
to how their characters approach a complex task which does require
preparation and planning, then make the resulting skill test Hard.

*As a Result of Good Roleplaying*

Usually, this happens with skills that involve some form of
communication, like Influence. When the player describes the action of
their character and roleplays the exchange between their character and
the non-player character(s). If the player was entertaining, kept in
character and added to the fun of the game, the Referee may award them a
+20% or +50% bonus. In exceptional circumstances, where the player
reduced everyone to tears of laughter or was outstanding in their
portrayal of their character, the Referee may waive the necessity for
the skill test entirely. Remember, good storytelling always comes before
any dice rolling.

Modifiers for Magic

Suppose the character is under the influence of a magic spell or item,
that gives them a penalty or bonus to the skill they are using. In this
case, the modifier for magic is added or subtracted after the modifier
for difficulty.

Like modifiers for difficulty, apply one modifier in any given skill
test. Pick the most powerful one, be it a bonus or a penalty.

Opposed Skill Tests

Opposed skill tests are made by both characters who are in direct
competition with each other. Both characters make the skill tests, as
usual, rolling 1D100 and attempting to roll equal to or under their
skill.

One Character Succeeds

If one character succeeds their skill test and the other fails, then the
successful character has won the opposed skill test.

Both Characters Succeed

If both characters succeed, then whoever rolled the highest in their
skill test wins the opposed test. If one character rolls a critical,
while the other rolls an ordinary success, then the character that
rolled the critical, which is a higher level of success, wins.

Both Characters Fail

Whoever rolled the lowest in their skill test wins the opposed test.

In the case of ties for both the player wins.

Difficulty Modifiers in Opposed Skill Tests

Only one side of the opposed skill test is modified. Either whoever has
the clear advantage or clear disadvantage. You do not modify both sides.

Magic in an Opposed Skill Test

Both sides can use magic in an opposed skill test, which generates skill
modifiers. Like a normal skill test these modifiers are applied after
the difficulty modifier.

*_Opposed Tests Results_*

[width="100%",cols="24%,20%,21%,18%,17%",]
|===
|*Player / Opponent* |*Critical* |*Success* |*Failure* |*Fumble*
|Critical |Highest Roll Wins |Player Wins |Player Wins |Player Wins
|Success |Opponent Wins |Highest Roll Wins |Player Wins |Player Wins
|Failure |Opponent Wins |Opponent Wins |Lowest Roll wins |Player Wins
|Fumble |Opponent Wins |Opponent Wins |Opponent Wins |Nobody Wins
|===

Skills at 100%

Characters with skills at the limit of 100% are Masters of that skill
and under normal circumstances do not fail and quite often can perform
tasks that are deemed impossible by ordinary people.

Skill Tests and Masters

Characters who have 100% with a particular skill never roll to test
their skill, and the outcome is an automatic critical. Because they do
not need to test their skill, they never fail or fumble skill tests with
that skill.

Opposed Tests vs Masters

In opposed skill tests characters with skills at 100% nearly always
succeed. There are two cases that need consideration.

If the player character is a Master and their opponent is also a Master.
In this case, the player rolls the dice as normal, and if they get a
critical, they win the contest. Otherwise, they tie, and the contest is
a standoff with neither side getting any advantage.

If the opponent is a Master and the character is not. The player rolls
the test for their character’s skill. The Master has already considered
to have a critical by the fact that they are at 100%, so the Referee
needs not roll. If player rolls a critical, the player character wins by
the barest and most amazing of margins. If the player succeeds, the
Master wins in less style than they normally would, which might be
impressive in its own right to any crowd watching. The player character
rolls a fail or fumble, they fumble.

Characters Whose skill is Modified to 100%

Characters who during a basic skill test or opposed skill contest have
their skill modified to 100%, are not treated as Masters. While a
modified skill of 100% still guarantees them a success, unless they
fumble a roll of 00, they still have to roll to see if they get a
critical.

Group Skill Tests

Sometimes the Referee will call for everyone around the table to make
the same skill test. These tests are made as individuals. For example, a
Perception Test to notice the bandits hidden in the bushes on either
side of the path the characters are currently travelling along. Those
characters who make their tests can act on the information that it
provides. Those who don’t can’t. Characters can also critical or fumble
as normal. Determining Surprise in the Combat chapter is another example
of this.

Assistance

Characters will often help each other during skill tests. Often such
assistance will break a deadlock where a character cannot successfully
do a task on their own. Only one assistance may be taken at a time, but
it may add to the modifier that the character making the skill test has
already gained. Note: If the character is doing this in combat, they act
on the turn of the character they are helping. They lose their own turn.
Therefore, they cannot assist if they have already acted in that round.

Assistance Procedure.

[arabic]
. Choose an appropriate skill, which need not be the same as the skill
which the character they are assisting is using. Make the skill roll and
narrate how your character is helping.
. The Referee determines if the character is actually in a position to
help.
. If the Referee approves, add +20% to the skill of the character you
are helping.

Skill Descriptions

Here is the full list of skills in alphabetical order.

Athletics (DEX+STR)

This broad skill covers a range of athletic activities useful to
adventuring characters, including acrobatics, climbing, jumping and
swimming.

_Acrobatics:_ This allows a character to perform a variety of gymnastics
and balancing tasks, such as tumbling, walking a tightrope or keeping
balance on a narrow or unstable ledge. The character can move at half
their normal speed across an unstable surface without penalty. To move
at a normal rate requires an Acrobatics test. A successful Acrobatics
test will also halve the damage suffered from falling.

_Brute Force:_ Brute force is an application of Athletics that relies
purely on power, with no finesse involved. Brute force involves pushing,
lifting or dragging.

_Climbing:_ Given enough hand and footholds, a character can climb any
surface, given enough time, without the need for a test. Under normal
circumstances, a character can ascend or descend one-quarter of their
Movement per Combat Round (see Chapter 5 Combat for details). A
character can double the rate of their climb or descent by making a Hard
Athletics test.

_Jumping:_ In general, a successful Athletics test allows a character to
jump up to twice their height horizontally or up to half their height
vertically, if they have at least five metres to run first. For standing
jumps, half these distances. For humans, average height is roughly 1.8m
which gives a jumping distance of 4m.

For greater distances, the Referee can apply a -20% or even -50%
penalty. If the distance involved is absurd, the Referee should feel
free to say the test is impossible

_Swimming:_ Characters usually swim at half their usual movement.
Athletics tests are only required when conditions are less than ideal –
swimming while heavily encumbered or in strong currents, for example.

Close Combat (DEX+STR)

This skill deals with the art of hitting things and defending the
character with melee weapons, such as swords, clubs, spears, polearms
and shields.

Craft(INT+10)

This skill is a grouping of several disciplines, that measures the
character’s ability to make and repair items.

As a very rough guide, it takes one day per 50 SP to produce an item.
The base cost of the article in materials needed is 50% of the listed
finished value.

Culture (Own) (INT+10) /Culture (Other) (INT)

Each Culture skill provides information about the prevailing worldview
of that group of people (or creatures), which includes history,
politics, weather cycles, geography, superstitions, and popular
mythology.

Culture (Own) is the worldview of the people by whom the character is
raised. All other foreign or alien cultures are Culture (Other). Culture
(Other) is a collection of skills, one for each culture.

== Deception (DEX+INT)

Deception covers the arts of:

_Disguise:_ Used to change a character’s appearance and adopt a
different outward persona.

_Sleight:_ Used to hide or take objects, without drawing undue
attention.

_Stealth:_ Used whenever a character attempts to evade detection by
another character personally. Usually, this happens when a character
either tries to creep past an enemy, hide from one, or performs a
combination of both.

When testing the skill, Deception is often opposed by the Perception
skill and is modified according to the situation. Note that attempts at
Fast Talk use the Influence skill rather than Deception.

Dodge (DEX+10)

The Dodge skill is used to avoid incoming objects that are swung or
thrown at the character. The skill is usually used when a character
attempts to dodge an incoming blow in combat or a physical hazard that
can be avoided, such as falling masonry.

Driving (DEX+INT)

If a character is driving a wagon, chariot, or similar vehicle, at no
more than walking pace across flat terrain, a Driving skill test will
never be required. Skill tests are needed when a character wants to do
something out of the ordinary with a vehicle – such as to travel across
treacherous terrain, jump obstacles and so on.

Engineering (INT+10)

This skill is used to design, build, activate, repair, sabotage or
disassemble large mechanisms or constructs, such as siege machines, city
gates and drawbridges, mine-shafts, sailing ships and so forth.

Healing (INT+10)

Use of this skill will always require a healer’s kit, which includes
suitable medical equipment, such as bandages and salves, or an
appropriate improvised alternative. Each use of the Healing skill
generally takes a few minutes to perform. Both characters must remain
stationary and may not use combat actions or reactions while this occurs
or they will lose the benefits of the healing.

See the following table for the range of Healing actions available to
the characters using this skill.

All healing actions are stressful, so they always require a skill test
to perform successfully.

*_Healing Actions_*

[width="100%",cols="30%,70%",]
|===
|*Injury or Ailment* |*Treatment*

|Unconsciousness |A successful Healing test can revive a character from
unconsciousness.

|Minor Injury (any wound taken while total hit points over zero) |A
successful Healing test on a Minor Injury will heal 1D6 Hit Points.

|Stabilise Mortal Wound (character less than zero hit points) |A
successful Healing test on a Mortal Wound (where hit points are less
than zero) will not restore the lost Hit Points. This Healing merely
stabilises the patient enough so that they will not die of blood loss.

|Curing Diseases |A successful Healing test allows a diseased patient to
add a bonus to his next opposed test of Resilience versus disease
Potency to resist the disease. The bonus is equal to the healer’s
Healing skill divided by 10.

|Curing Poisons |A successful Healing test allows a poisoned patient to
attempt a second opposed test of Resilience versus poison Potency. The
patient gains a bonus to their Resilience skill equal to the healer’s
Healing skill divided by 10.

|Surgery |Other than magical healing, successful Surgery is the only way
that a character can recover from a Mortal Wound. Once a successful
Healing test has been made to quench the bleeding of a Mortal Wound, a
successful Healing test can attempt to set broken bones, stitch together
rent flesh and restore the wound location so that it is on the road to
recovery. If the Healing test is a success, the stricken character gains
one hit point and will begin to heal as usual.
|===

Influence (CHA+10)

This skill is the art of verbally persuading another character to do
what you want.

Influence skill tests are usually opposed by either Persistence (as a
measure of sheer bloody-minded will power) or Influence (where the
character argues back). They are further modified by how much a
character is trying to change an opponent’s mind. Influence skill tests
are often modified by how well the player roleplays the exchange (see
“When the Referee should apply difficulty modifiers” above).

Influence can be used in one of three ways.

* _Fast Talk_. The character tries to quickly confuse either an
individual or small group with a clear leader, into doing what they
want.
* _Oratory._ The character puts forward a series of arguments to sway a
large crowd of people.
* _Intimidation_. The character tries to use the threat of violence
against an opponent or group of opponent.

See the Social Combat section for more.

Language (Own) (Int+50)/Language (Other) (INT)

The Language skill is several separate skills grouped under a single
heading. Language (Gatanese), Language (Dark Lander) and Language
(Goblinoid), for example, are all individual skills.

Every character with a Language skill of 50% or more is fluent in that
language, although they are likely to have an accent if it is not their
native language.

A score in a Language skill of 80% or more will mean the character can
also read and write in that language.

Lore (Area of Knowledge) (INT)

The Lore skill is an umbrella term for several different skills, each of
which must be improved separately.

Each Lore skill defines an area of knowledge for the character, and
whenever a player wants to see if their character knows something about
the subject at hand they use that specific Lore skill.

A player’s imagination is the only limit to the range of possible Lores.
Example Lores include: alchemy, art, astronomy, gambling, geography,
heraldry, law, logistics, military tactics, philosophy, poisons.

Mechanisms (DEX+INT)

The Mechanisms skill is used for picking a lock or disassembling a trap.
Usually, this takes at least one minute (12 combat rounds) to perform,
whereas larger or particularly complex devices will take longer.

Usually, a character will merely make a Mechanisms test to succeed at
assembling or disassembling a device, with appropriate bonuses or
penalties decided upon by the Referee. If a device has been designed to
resist attempts at disassembly specifically, the Mechanisms test becomes
opposed by the Mechanisms skill of the character who created it.

Natural Lore (INT+10)

Broadly speaking, this Lore deals with the character’s knowledge of the
natural world. It can be broken into five specialist areas.

_Animal:_ This covers the ability to recognise an animal, know its
feeding habits, breeding cycle, habitats and so on. A character with a
skill of at least 50% may try to domesticate a wild animal, making a
skill test after every full week of training. If the character also has
a Riding skill of at least 50% and the animal is capable of being
ridden, they may train the animal to be ridden during this period. The
character may later train the animal not to panic in battle and to
strike at his enemies, after a further period of training, with the
character making a skill test at the end of each week to succeed.

_Plant:_ A character can identify plants in the wild, discover the right
places to grow crops, decide which plants are edible and what unusual
properties they may possess.

_Mineral:_ This skill allows the character to detect precious metals and
stones, detect fault lines and other dangerous features in the rock,
etc.

_Survival:_ One Survival test will be required every day that a
character lacks either food, water or a safe place to sleep. Success
indicates the character manages to find whatever they lack – failure
means they will go without, which over several days could result in
severe consequences. Survival tests aren’t called for when the character
is in a city or town.

_Tracking:_ With this skill, a character can locate the tracks of a
specific creature and follow them while in the wilderness.

_Weather:_ The character can predict changes in the climate.

Perception (INT+POW)

The Perception skill is used to represent the five senses of the
character when detecting objects or other characters. For example, a
typical use of the Perception skill is as a straight skill test to
identify hidden objects in a room or as an opposed test to discover a
hidden character.

Performance (CHA+10)

A successful test with this skill will result in the audience or partner
being pleased by the character’s performance. This skill covers acting,
composing poetry, dancing, singing, readings and playing an instrument.

Persistence (POW+10)

Persistence represents a character’s mental willpower. It is used to
resist the effects of magic and to resist another character’s attempt to
use the Influence skill against them.

Personal Magic Casting (POW X 3)

This skill represents the character’s ability to cast Personal Magic
spells. It also describes their knowledge about Personal Magic (see the
dedicated chapter for further details).

Ranged Combat (DEX+ INT)

This skill covers the use of missile weapons, such as bows, crossbows,
thrown spears and thrown daggers. See the Combat chapter for more
detail.

Religion (Own) (INT+10)/Religion(Other)(INT)

Religion is used to recall knowledge of a religious nature, though the
character will only be able to remember knowledge pertinent to the
specified religion.

Learning Religion (Own) requires a character to be at least a lay member
of a religion. Normally, a character will only be a member of one
religion. So, Religion (Other) usually relates to foreign religions and
is learned through observation or being taught by a member of the
religion in question.

The Religion skill is not needed actually to cast Divine magic. Still,
it is used to advance in status and power within the Religions that the
character is a member of and to grant access to higher magnitudes of
Divine magic.

Resilience (CON+POW)

A measure of how physically tough a character is. The higher a
character’s Resilience, the more likely they are to handle adverse
physical conditions, such as weathering a vicious sandstorm, surviving
in a drought or overcoming the effects of poison or disease.

Riding (DEX+POW)

If a character is riding a creature with the help of saddle and
stirrups, at no more than a walking pace across flat terrain, then a
Riding test will never be required. Tests are required when a character
wants to do something out of the ordinary with a mount – such as travel
across treacherous terrain, jump obstacles, ride bareback and so on.

Sailing (DEX+INT)

This skill covers small water-borne craft propelled manually by oars or
paddles, commonly known as boats, and larger craft powered by sail or
rows of oars. Travelling across calm water does not usually require a
skill test, but adverse conditions such as currents and weather can
bestow penalties.

Sorcery Casting (INT)

This skill covers the successful casting of Sorcery spells which the
caster knows, and also the ability to manipulate the effects, range and
duration of those spells. This skill also allows the use of magic items
with stored spells (commonly called Matrices) and scrolls with Sorcery
spells written on them. It can also be used to represent the character’s
knowledge of Sorcery and its works. See the Sorcery Chapter for details.

Streetwise (CHA+POW)

Streetwise allows a character to find fences for stolen goods, black
markets and uncover general information in an urban setting. Such uses
of Streetwise usually require a minimum of 1D4 hours. Streetwise also
covers following people down crowded city streets.

Trade (INT+10)

This skill is used when characters trade, barter or otherwise negotiate
over the sale of goods. In such transactions, a successful opposed test
using the Trade of the buyer versus the Trade of the seller is needed
for the buyer to get the best deal. If the buyer wins, they receive a
discount, -10% for success, -20% for a critical. If the seller wins, the
price that they can sell the item for increases by +10% for success and
+20% for a critical. If the opponent fumbles their roll, double the
increase or decrease.

The Trade skill also enables the character to determine the value placed
on something by others; by estimating its market value. Everyday or
obscure objects might give a bonus or penalty to the skill test. Success
will allow a character to guess the average monetary value of the
object, usually guessing accurately to within 10% of its actual value.

Unarmed Combat (DEX+STR)

This skill covers the use of natural attacks. For humans, this is
punching, kicking, and grappling. Non-human characters may also have
bite, horn, claw and tail attacks.

[width="100%",cols="29%,71%",]
|===
|*Weapon* |*Damage Dice*

|Unarmed |1D4

|Natural weaponry |As noted, typically 1D4 to 1D12 depending on the
creature (see Creature Chapters)
|===

Wealth (Optional) (INT+CHA)

This skill shows the resources and physical possessions a character has.
For a beginning character, it is based upon what they have earned using
their wits and charm alone. The basic skill is (INT + CHA), and this can
be increased by spending skill points at character generation. If you
are determining starting wealth by social class, set the minimum in the
skill according to social rank (i.e. the base score as shown in the
table below). For example, a Minor Noble would have a Wealth of 86%.

Wealth can be used as an abstract measure of material resources in the
game. A character who has the equivalent Wealth level to a piece of
equipment’s purchase cost can automatically buy it. If the piece of
equipment’s cost is one level above the character’s wealth, then the
character will need to make a wealth test.

If they succeed, the item is theirs. The next wealth test is at -20%.
This modifier lasts for a month.

If they fail, they do not have enough spare cash at the time that they
try to buy the item and must free up some of their savings or wait until
they are paid again at the end of their current job.

If they fumble, they will find that they have a cash flow problem and
cannot make any Wealth tests for at least a month, and they must spend
time and effort sorting out their financial difficulties.

If they roll a critical, they find they have more than enough disposable
income and can make their next Wealth test without a penalty.

*_What Wealth Means_*

[width="100%",cols="12%,15%,13%,18%,18%,24%",options="header",]
|===
|*Wealth %* |*Description* |*Social Class* |*Financial Situation.*
|*Equipment* |*Housing*
|0 and lower |Destitute |Beggars and the displaced. |Outside of the
normal economy and unable to support themselves. |Rags, discarded tools,
subsistence food- usually scraps. |Streets or in a slum.

|1-34% |Poor |Labourers, low ranking Crafters, Militiamen. |Has genuine
financial difficulties, money comes and goes at an alarming rate. |Basic
clothes, knives, clubs, gruel, occasional poor cut of meat. Rents tools
of the trade. |In crowded shared accommodation. If in the city, it’s
owned by someone else.

|35-65% |Average |Freemen with a trade. |What is considered the average
for the Culture. Able to live within their means, but still vulnerable
to cash flow problems. |Swords spear, shield, bow, crossbow, leather
armour, good meat once a week. The character owns the tools of their
trade. |A reasonable dwelling for self and immediate family, owned by
them.

|66-85% |Well off |Minor merchants, Priests. |They have a comfortable
lifestyle with savings if the character is prudent. Unlikely to have any
cash problems. |Ringmail armour, longbow and sword, good meat 2-3 times
a week. They own an excellent set of trade tools. They have 1-2
servants. |Owns a private residence for their own family with room to
spare.

|86-90% |Wealthy |Merchants, Minor Nobility. |Extravagant lifestyle paid
for by investments in ventures in which others do the actual work.
|Chain or even plate mail armour, and weapons. They have a choice of the
best food. They have a staff of 2-12 servants. |They live in a villa
with spacious rooms for extended family and servants.

|100% |Rich |Kings, powerful Nobles. |As above but more so. Supports a
large entourage as well as extended family, who all depend upon ruler
for their extravagant lifestyle. |Custom made plate mail and weapons.
Regularly holds feasts for the entire court. They have an entourage of
3-18 hangers-on, a bodyguard of 2-12 warriors, 50+ servants. |A
palace/castle with space for their family, hangers-on and staff.

|Beyond 100% (outside of normal ranking) |Super Rich |Emperors. |Lives
in a constant state of opulent extravagance. |Armour custom made with
gold leaf decoration, weapons encrusted with jewels. |A grand palace
complex which is the size of a small city, often within the walls of a
larger outer city.
|===

== 
