= OpenQuest 3rd Edition System Resource Document

A copy of the OpenQuest 3rd Edition SRD (v1.2, 09.03.2023), kept here as a reference for development of this
system. The official version is available at https://openquestrpg.com/srd.

== Contents

* xref:OQ3-SRD-Characters.adoc[Characters]
* xref:OQ3-SRD-Skills.adoc[Skills]
* xref:OQ3-SRD-Combat.adoc[Combat]
* xref:OQ3-SRD-Equipment.adoc[Equipment]
* xref:OQ3-SRD-Spot-Rules.adoc[Spot Rules]
* xref:OQ3-SRD-Personal-Magic.adoc[Personal Magic]
* xref:OQ3-SRD-Divine-Magic.adoc[Divine Magic]
* xref:OQ3-SRD-Sorcery.adoc[Sorcery]
* xref:OQ3-SRD-Creatures.adoc[Creatures]
* xref:OQ3-SRD-Loot.adoc[Loot]

== Licence

This work is based on the OpenQuest System Resource Document (found at https://openquestrpg.com/srd), a D101 Games
product developed, authored by Newt Newport with Paul Mitchener. OpenQuest System Resource Document © 2021 by Newt
Newport with Paul Mitchener is licensed under Attribution 4.0 International. To view a copy of this license,
visit http://creativecommons.org/licenses/by/4.0/

=== Changes

The original `.docx` files were converted to AsciiDoc and renamed. The text was not intentionally edited, but formatting
may differ from the original.

=== Scope

The contents of this directory are licensed under CC BY 4.0, not under the WTFPL that covers the rest of this
repository's source code.

OpenQuest is the trademark of Paul Newport, used with Permission.
